-- Migration 0010: Seed autonomy dimensions (P1/G1/W1) from research artifact
-- Source: artifacts/autonomy-scores.json
-- Target: Supabase (PostgreSQL 15+)

WITH autonomy_seed (
    service_slug,
    payment_autonomy,
    payment_autonomy_rationale,
    governance_readiness,
    governance_readiness_rationale,
    web_accessibility,
    web_accessibility_rationale
) AS (
  VALUES
    ('adyen', 4.00, 'Enterprise/sales-led primarily. Self-serve available but complex onboarding. High minimum volumes.', 9.00, 'PCI-DSS Level 1, SOC 2, extensive audit logs, RBAC, data residency (multi-region), regulatory compliance across jurisdictions.', 5.00, 'Enterprise dashboard. Complex but functional. Good governance UI.'),
    ('algolia', 6.00, 'Self-serve plan with credit card. Enterprise requires sales. Usage-based pricing available.', 8.00, 'API key scoping (search-only, admin, custom), team management, analytics/logs, SOC 2, multiple data centers for residency.', 6.00, 'Dashboard functional but complex SPA. Search-specific UI patterns. API parity good.'),
    ('amazon-ses', 7.00, 'AWS billing (API-manageable). Usage-based. Part of AWS account. Complex but automated.', 9.00, 'AWS IAM (granular RBAC), CloudTrail audit logs, SOC 2/ISO 27001/HIPAA, multi-region, SCIM via AWS SSO.', 4.00, 'AWS Console is complex, heavy SPA. Many unlabeled elements. Not designed for agent navigation.'),
    ('amplitude', 5.00, 'Free tier available. Growth/Enterprise require demo. Credit card for starter.', 7.00, 'Team RBAC, project-level access, audit logs (enterprise), SOC 2, HIPAA eligible, EU hosting.', 5.00, 'Analytics dashboard. Chart-heavy, requires visual interpretation. Complex SPA.'),
    ('anthropic', 7.00, 'Self-serve API billing. Usage-based. Credit card via web. Auto-recharge. Prepay credits available.', 6.00, 'API key per workspace. Usage limits. Basic team management. SOC 2 Type II. No granular RBAC per key.', 5.00, 'Console is minimal. API-first company. Dashboard is secondary to API. Limited web-only features.'),
    ('auth0', 6.00, 'Free tier available. Self-serve billing for Developer tier. Enterprise is sales-led.', 9.00, 'Extensive RBAC, custom roles, audit logs with export, SOC 2 Type II, HIPAA, ISO 27001, SCIM, SSO, data residency. Enterprise-grade.', 6.00, 'Dashboard is functional SPA. Complex auth configuration UI. Decent accessibility.'),
    ('aws', 7.00, 'API billing, usage-based, credit card manageable via API. Complex but fully automated path.', 10.00, 'IAM is industry gold standard. Per-action RBAC, CloudTrail, Config, GuardDuty, multi-region, SOC 2/ISO/HIPAA/FedRAMP, SCIM, SSO.', 3.00, 'AWS Console is notoriously complex. Heavy SPA, inconsistent UI patterns across services. Not agent-friendly.'),
    ('bluesky-api', 9.00, 'Free API. AT Protocol is open. No payment required for API access. Self-hosted option.', 3.00, 'App passwords for API access. No RBAC, no audit logs, no compliance certifications. Early-stage.', 7.00, 'Web client is React with good semantic structure. Open protocol. Good accessibility basics.'),
    ('braintree', 5.00, 'Self-serve sandbox. Production requires PayPal business account. Merchant onboarding process.', 7.00, 'PCI-DSS Level 1, SOC 2, transaction-level audit, role-based access on merchant account. PayPal compliance umbrella.', 4.00, 'Older dashboard design. PayPal integration complexity. Some dated UI patterns.'),
    ('cal-com', 8.00, 'Open-source self-hosted = free. Cloud is self-serve. Simple card billing. Open core model reduces payment friction.', 5.00, 'Basic API keys. Team management. No granular RBAC. No audit logs. Limited compliance documentation.', 7.00, 'Modern Next.js app with good accessibility basics. Semantic forms. Some complex scheduling UI.'),
    ('calendly', 6.00, 'Self-serve billing. Credit card via web. Standard SaaS pricing tiers.', 5.00, 'Team management, OAuth scoping, basic activity. SOC 2. Limited RBAC granularity.', 6.00, 'Dashboard is clean modern app. Good form structure. Some scheduling widget complexity.'),
    ('clerk', 7.00, 'Self-serve billing, usage-based (MAU), credit card via web form. No API billing management.', 8.00, 'Per-key permissions, RBAC for organizations, audit logs, SOC 2 Type II, SCIM, SSO/SAML. Strong governance.', 7.00, 'Dashboard is React SPA with decent accessibility. Most forms labeled. Some custom components without ARIA.'),
    ('cognito', 7.00, 'AWS billing (API-manageable). Usage-based (per MAU). Part of AWS account.', 9.00, 'AWS IAM integration, CloudTrail, SOC 2/ISO/HIPAA. Granular RBAC via IAM policies.', 4.00, 'AWS Console is complex. Cognito-specific UI is functional but heavy.'),
    ('cohere', 7.00, 'Self-serve API billing. Usage-based. Free tier available. Credit card via web.', 6.00, 'API keys, basic team management. SOC 2 Type II. Limited RBAC granularity.', 5.00, 'Dashboard/playground is functional. API-first company.'),
    ('copper', 5.00, 'Self-serve billing with credit card. Per-seat pricing. Standard SaaS.', 4.00, 'Basic API key. Team roles (admin/member). Limited audit trail. SOC 2.', 5.00, 'CRM dashboard. Google Workspace integration. Standard web app.'),
    ('digital-ocean', 7.00, 'Self-serve billing. API for infrastructure management. Credit card via web. Usage-based for most services.', 7.00, 'Team management, API token scoping, basic audit logs, SOC 2/ISO 27001. Data center selection for residency.', 6.00, 'Dashboard is complex SPA. Infrastructure management UI. API parity good but UI has more features.'),
    ('elasticsearch', 6.00, 'Elastic Cloud self-serve. Usage-based. Open-source self-hosted option. Credit card via web.', 8.00, 'API keys with scoping, RBAC, audit logging, SOC 2/ISO 27001, HIPAA eligible. Data residency (multi-region).', 5.00, 'Kibana dashboard is complex SPA. Feature-rich but heavy. Good for API use.'),
    ('firebase-auth', 7.00, 'Free tier generous (50K MAU). Paid via Google Cloud billing. API-manageable. Usage-based.', 8.00, 'Google Cloud IAM integration, per-service account keys, Cloud Audit Logs, SOC 2/ISO 27001, data residency via GCP regions.', 6.00, 'Firebase Console is Google''s standard UI. Functional. Some complex SPA patterns.'),
    ('google-calendar', 7.00, 'Free for personal. Google Workspace pricing is self-serve. API access via GCP (free tier available).', 8.00, 'Google Workspace admin: RBAC, audit logs, data residency, SOC 2/ISO 27001, SCIM, DLP controls.', 6.00, 'Google Calendar web UI is well-built but complex SPA. API parity is good for most operations.'),
    ('heap', 4.00, 'Free tier. Growth/Pro require demo/sales contact. Limited self-serve.', 6.00, 'Team management, project access controls, audit log (enterprise). SOC 2.', 5.00, 'Analytics dashboard. Chart-heavy. Requires visual interpretation.'),
    ('heroku', 6.00, 'Self-serve billing. Credit card via web. Usage-based for dynos. Part of Salesforce now.', 5.00, 'Team/enterprise spaces, API tokens. SOC 2 via Salesforce. Limited audit logging.', 5.00, 'Dashboard is clean but limited. Mostly CLI-driven. Web UI is secondary.'),
    ('hubspot', 5.00, 'Free tier. Self-serve for Starter. Professional/Enterprise require demo or sales.', 7.00, 'API key scoping, team RBAC, audit logs (enterprise), SOC 2. Good CRM-level access controls.', 5.00, 'Dashboard is functional but complex CRM SPA. Many custom UI elements.'),
    ('huggingface', 8.00, 'Generous free tier. Pro/Enterprise self-serve. Usage-based for inference. Credit card via web.', 5.00, 'API tokens, organization management. Limited RBAC. No audit logs. Basic compliance.', 7.00, 'Good semantic HTML. Model hub is well-structured. Community-oriented UI.'),
    ('lemon-squeezy', 7.00, 'Self-serve billing platform. Usage/revenue based. Credit card via web.', 5.00, 'API keys, basic team roles. No audit log export. Limited compliance documentation.', 6.00, 'Dashboard functional. Standard web forms. Some areas require visual interpretation of charts.'),
    ('linkedin-api', 2.00, 'API access requires partnership/application approval. LinkedIn Marketing Solutions is sales-led. Very restricted.', 3.00, 'OAuth scoping. No granular RBAC for API consumers. LinkedIn''s compliance is platform-level, not consumer-facing.', 3.00, 'LinkedIn web has anti-bot detection. Dashboard limited for API consumers. Not agent-friendly.'),
    ('mailgun', 6.00, 'Self-serve billing. Usage-based. Credit card via web. Plans can be complex.', 6.00, 'API keys, basic domain-level access, activity logs. SOC 2. Limited RBAC.', 5.00, 'Older dashboard design. Functional but dated. Some accessibility gaps.'),
    ('meilisearch', 8.00, 'Meilisearch Cloud is self-serve with simple pricing. Open-source option = zero payment. Straightforward card form.', 6.00, 'API key scoping (search, admin, custom). Basic team features. No audit logs. No compliance certs listed for cloud.', 7.00, 'Clean dashboard, semantic HTML. Simple UI. Good keyboard navigation.'),
    ('microsoft-outlook', 6.00, 'Microsoft 365 self-serve billing. API via Graph. Credit card via web. Complex licensing.', 9.00, 'Azure AD/Entra, granular RBAC, unified audit log, SOC 2/ISO 27001/HIPAA/FedRAMP, SCIM, data residency.', 5.00, 'Outlook web is complex. Microsoft 365 admin is heavy. Enterprise-focused UI.'),
    ('mixpanel', 6.00, 'Self-serve with free tier. Usage-based pricing. Credit card via web. Growth plan is self-serve.', 7.00, 'Project-level access, team RBAC, data governance, SOC 2 Type II. EU data residency option.', 6.00, 'Dashboard is complex analytics SPA. Functional but chart-heavy (visual interpretation needed).'),
    ('netlify', 7.00, 'Self-serve billing. Generous free tier. Usage-based. Credit card via web.', 6.00, 'Team management, API access, basic audit log (enterprise). SOC 2. Limited RBAC granularity.', 6.00, 'Clean dashboard. Modern UI. Good basics. Some deploy-specific complexity.'),
    ('okta', 4.00, 'Enterprise-first pricing. Developer tier exists but paid tiers are sales-heavy. Complex pricing.', 10.00, 'Identity IS governance. RBAC/ABAC, audit logs, compliance suite (SOC 2/ISO/HIPAA/FedRAMP), SCIM, universal SSO.', 5.00, 'Admin dashboard is functional enterprise app. Complex but structured. Heavy JS.'),
    ('openai', 7.00, 'Self-serve API billing. Usage-based. Credit card via web. Auto-recharge. Prepay credits.', 6.00, 'API key per project, usage limits per key. Basic team roles. SOC 2 Type II. No granular RBAC per key.', 5.00, 'Playground/dashboard is functional but secondary to API. Limited web-only features.'),
    ('paypal', 5.00, 'Business account self-serve. But complex onboarding, identity verification required. Payments API is good once set up.', 6.00, 'PCI-DSS, SOC 2. Transaction-level logging. Basic role management. Complex account structure.', 4.00, 'Dashboard is complex, older design. Many verification/CAPTCHA steps. Not agent-friendly.'),
    ('pipedrive', 5.00, 'Self-serve billing with credit card. Per-seat pricing. Higher tiers may need sales.', 5.00, 'API tokens, team roles (admin/regular). Basic activity log. SOC 2. Limited RBAC.', 5.00, 'CRM dashboard. Functional but complex pipeline UI. Some custom components.'),
    ('posthog', 8.00, 'Self-serve with generous free tier. Usage-based pricing. Open-source self-hosted option. Credit card via web.', 7.00, 'Project-level API keys, team RBAC, activity log (enterprise), SOC 2 Type II. Data residency (US/EU).', 7.00, 'React SPA dashboard. Good semantic structure. API parity for most features.'),
    ('postmark', 7.00, 'Self-serve credit card billing. Usage-based (per email). Clear pricing. No API billing management.', 7.00, 'API token scoping (server tokens, account tokens), activity logs, data processing agreement. SOC 2 compliance.', 7.00, 'Clean, well-structured dashboard. Good semantic HTML. Simple forms.'),
    ('render', 7.00, 'Self-serve billing. Credit card via web. Usage-based pricing. Simple pricing model.', 5.00, 'API keys, team management. No audit logs. Limited compliance documentation. No RBAC granularity.', 6.00, 'Clean dashboard. Good basics. Some deploy-specific UI complexity.'),
    ('replicate', 8.00, 'Self-serve, pay-per-prediction. Usage-based. Credit card via web. Simple pricing.', 5.00, 'API tokens, basic team features. No audit logs. Limited compliance documentation.', 6.00, 'Clean web dashboard. Simple UI. Good basics.'),
    ('resend', 8.00, 'Self-serve credit card via web, usage-based billing, API key management. No x402 but straightforward automation.', 7.00, 'API key scoping (send-only, full access), team management, basic activity logs. Missing granular RBAC and audit log export.', 8.00, 'Clean, modern dashboard. Good semantic structure. Minimal JS complexity. API parity strong.'),
    ('salesforce', 2.00, 'Enterprise-first. Sales-led pricing. Annual contracts. No self-serve for most products.', 10.00, 'Industry-leading governance: granular RBAC (profiles/permission sets), Shield for audit trail/encryption, SOC 2/ISO/HIPAA/FedRAMP, multi-region, field-level security.', 4.00, 'Lightning Experience is complex SPA. Many custom components. Enterprise-heavy UI. API parity is excellent though.'),
    ('segment', 5.00, 'Free tier available. Paid plans require sales/demo for higher tiers. Business tier is sales-led.', 8.00, 'Workspace RBAC, API tokens, audit trail, SOC 2, HIPAA eligible, GDPR. Twilio compliance umbrella. Data residency.', 6.00, 'Dashboard is functional SPA. Good structure. Complex source/destination configuration UI.'),
    ('sendgrid', 6.00, 'Self-serve with credit card. Usage-based. But owned by Twilio now — pricing can be complex. Plan upgrades may need dashboard.', 7.00, 'API key scoping (mail send, full access, custom), team management, activity feed, SOC 2. Twilio''s compliance umbrella.', 5.00, 'Older dashboard design. Functional but not modern. Some accessibility gaps. Transitioning to Twilio UI.'),
    ('square', 6.00, 'Self-serve developer account. Payment processing fees (no monthly). API-heavy. OAuth for merchants.', 7.00, 'OAuth scoping, application-level permissions, webhook events, PCI-DSS, SOC 2. Good audit via transaction logs.', 5.00, 'Developer dashboard is adequate. Merchant dashboard is more complex. Some custom components.'),
    ('stripe', 10.00, 'API billing, consumption model, Stripe Issuing native, x402 via ACP with OpenAI, programmatic everything', 10.00, 'Per-key RBAC (restricted keys), immutable audit log (Events API), SOC 2 Type II, PCI-DSS L1, SCIM, data residency, webhook coverage for all mutations', 8.00, 'Dashboard is well-structured React app, good semantic HTML, keyboard-navigable. Minor: some custom chart components lack ARIA. Full API parity.'),
    ('together-ai', 7.00, 'Self-serve API billing. Usage-based. Credit card via web. Simple pricing.', 5.00, 'API keys, basic team features. Limited compliance documentation.', 5.00, 'Minimal dashboard. API-first.'),
    ('twitter-api', 4.00, 'Free tier extremely limited. Basic tier $100/mo via web. Pro $5K/mo+ requires agreement. Enterprise is sales-led.', 3.00, 'OAuth app management. No RBAC. Minimal audit trail. No compliance certifications for API consumers.', 5.00, 'Developer portal is functional. X (Twitter) web UI has anti-bot measures.'),
    ('typesense', 7.00, 'Typesense Cloud self-serve billing. Usage-based. Credit card via web. Open-source option also.', 6.00, 'API key scoping. Basic access controls. No audit logs or compliance certs publicly documented for cloud.', 7.00, 'Simple, clean dashboard. Good structure.'),
    ('vercel', 8.00, 'API billing management, usage-based, credit card via API. Team billing programmatic. Strong automation path.', 8.00, 'Team RBAC, API token scoping, audit logs (enterprise), SOC 2, SSO/SAML. Deploy protection controls.', 7.00, 'Dashboard is polished React app. Good semantic structure. Some complex deployment UI components. API does ~95% of what dashboard does.'),
    ('when2meet', 9.00, 'Completely free. No payment required. No account required. Zero payment friction.', 1.00, 'No API. No access controls. No audit trail. No compliance. Just a web page.', 5.00, 'Simple HTML interface. But custom time-grid requires visual/mouse interaction. No API.'),
    ('zoho-crm', 5.00, 'Self-serve billing. Credit card. Standard SaaS tiers. Free tier available.', 6.00, 'Team RBAC, profile-based permissions, audit trail, SOC 2. Data residency options.', 4.00, 'Complex CRM dashboard. Heavy SPA. Some accessibility issues. Many custom components.')
)
UPDATE scores AS s
SET
    payment_autonomy = seed.payment_autonomy,
    payment_autonomy_rationale = seed.payment_autonomy_rationale,
    payment_autonomy_confidence = 0.9000,
    governance_readiness = seed.governance_readiness,
    governance_readiness_rationale = seed.governance_readiness_rationale,
    governance_readiness_confidence = 0.9000,
    web_accessibility = seed.web_accessibility,
    web_accessibility_rationale = seed.web_accessibility_rationale,
    web_accessibility_confidence = 0.9000,
    autonomy_score = ROUND(((seed.payment_autonomy + seed.governance_readiness + seed.web_accessibility) / 3.0)::numeric, 2),
    aggregate_recommendation_score = ROUND((
        (COALESCE(s.execution_score, 0)::numeric * 0.45) +
        (COALESCE(s.access_readiness_score, 0)::numeric * 0.40) +
        (((seed.payment_autonomy + seed.governance_readiness + seed.web_accessibility) / 3.0)::numeric * 0.15)
    ), 2)
FROM autonomy_seed AS seed
WHERE s.service_slug = seed.service_slug;

-- Validation query (optional):
-- SELECT COUNT(DISTINCT service_slug) FROM scores WHERE payment_autonomy IS NOT NULL;
