-- Migration 0084: Schema reconciliation for migrations 0051-0063
-- These migrations used wrong column names and targeted non-existent tables.
-- This reconciliation inserts the data into the correct tables.
--
-- Source: 122 capabilities, 383 mappings from 0051-0063
-- Author: Helm (rhumb-access)
-- Date: 2026-03-22

BEGIN;

-- ============================================================
-- STEP 1: Insert capabilities with correct schema
-- Original schema: (id, domain, action, description, input_hint, outcome)
-- 0051-0063 used wrong schema: (id, domain, description, status)
-- ============================================================

INSERT INTO capabilities (id, domain, action, description) VALUES
  ('translate.text', 'translation', 'text', 'Translate text between languages'),
  ('translate.detect_language', 'translation', 'detect_language', 'Detect the language of a text string'),
  ('translate.batch', 'translation', 'batch', 'Translate multiple strings in a single request'),
  ('image.resize', 'image', 'resize', 'Resize or crop an image to specified dimensions'),
  ('image.optimize', 'image', 'optimize', 'Compress/optimize an image for web delivery'),
  ('image.analyze', 'image', 'analyze', 'Extract labels, objects, or text from an image'),
  ('currency.convert', 'currency', 'convert', 'Convert an amount between two currencies'),
  ('currency.get_rates', 'currency', 'get_rates', 'Fetch current or historical FX rates'),
  ('maps.geocode', 'maps', 'geocode', 'Convert an address or place name to coordinates'),
  ('maps.directions', 'maps', 'directions', 'Get turn-by-turn directions between two points'),
  ('nlp.extract_entities', 'nlp', 'extract_entities', 'Extract named entities (people, places, orgs) from text'),
  ('nlp.sentiment', 'nlp', 'sentiment', 'Analyze sentiment and tone of text'),
  ('nlp.summarize', 'nlp', 'summarize', 'Produce an abstractive or extractive summary of text'),
  ('pdf.convert', 'pdf', 'convert', 'Convert a document or web page to PDF'),
  ('pdf.merge', 'pdf', 'merge', 'Merge multiple PDF files into one'),
  ('pdf.extract_text', 'pdf', 'extract_text', 'Extract plain text or structured data from a PDF'),
  ('file.convert', 'file', 'convert', 'Convert a file from one format to another'),
  ('file.compress', 'file', 'compress', 'Compress a file or archive into zip/tar/etc'),
  ('barcode.generate', 'barcode', 'generate', 'Generate a QR code or barcode image'),
  ('barcode.scan', 'barcode', 'scan', 'Decode a barcode or QR code from an image'),
  ('phone.validate', 'phone', 'validate', 'Validate a phone number format and carrier lookup'),
  ('phone.lookup', 'phone', 'lookup', 'Look up carrier, line type, and location for a number'),
  ('phone.send_otp', 'phone', 'send_otp', 'Send a one-time passcode via SMS for verification'),
  ('calendar.create_event', 'calendar', 'create_event', 'Create a calendar event with attendees and details'),
  ('calendar.check_availability', 'calendar', 'check_availability', 'Check free/busy availability for one or more users'),
  ('url.shorten', 'url', 'shorten', 'Shorten a long URL to a compact link'),
  ('url.expand', 'url', 'expand', 'Expand a short URL to its destination'),
  ('social.get_profile', 'social', 'get_profile', 'Fetch a public profile from a social platform'),
  ('social.post', 'social', 'post', 'Post content to a social platform'),
  ('social.search', 'social', 'search', 'Search posts or accounts on a social platform'),
  ('weather.current', 'weather', 'current', 'Get current weather conditions for a location'),
  ('weather.forecast', 'weather', 'forecast', 'Get multi-day weather forecast for a location'),
  ('weather.historical', 'weather', 'historical', 'Retrieve historical weather data for a date and location'),
  ('tax.calculate', 'tax', 'calculate', 'Calculate sales tax or VAT for a transaction'),
  ('tax.validate_vat', 'tax', 'validate_vat', 'Validate a VAT number and retrieve business details'),
  ('dns.lookup', 'dns', 'lookup', 'Resolve a domain name to IP addresses'),
  ('dns.whois', 'dns', 'whois', 'Retrieve WHOIS registration data for a domain'),
  ('crypto.get_price', 'crypto', 'get_price', 'Get current price of a cryptocurrency'),
  ('crypto.get_rates', 'crypto', 'get_rates', 'Get exchange rates for multiple crypto assets'),
  ('crypto.verify_address', 'crypto', 'verify_address', 'Validate a crypto wallet address format and checksum'),
  ('validate.email', 'validate', 'email', 'Validate email address format, MX records, and deliverability'),
  ('validate.address', 'validate', 'address', 'Validate and normalize a postal address'),
  ('validate.vat', 'validate', 'vat', 'Validate a VAT/tax ID number for a given country'),
  ('video.transcode', 'video', 'transcode', 'Transcode a video file to a different format or resolution'),
  ('video.thumbnail', 'video', 'thumbnail', 'Extract a thumbnail image from a video at a given timestamp'),
  ('video.subtitle', 'video', 'subtitle', 'Generate or embed subtitles/captions for a video'),
  ('notification.push', 'notification', 'push', 'Send a push notification to a mobile device or browser'),
  ('notification.in_app', 'notification', 'in_app', 'Deliver an in-app notification message to a user'),
  ('spreadsheet.read', 'spreadsheet', 'read', 'Read rows or ranges from a spreadsheet file'),
  ('spreadsheet.write', 'spreadsheet', 'write', 'Write or append rows to a spreadsheet file'),
  ('esign.create_request', 'esign', 'create_request', 'Create a document signing request'),
  ('esign.get_status', 'esign', 'get_status', 'Check the status of a signing request'),
  ('workflow.trigger', 'workflow', 'trigger', 'Trigger an existing workflow or automation'),
  ('workflow.create', 'workflow', 'create', 'Create a new workflow or zap from a template'),
  ('monitoring.create_alert', 'monitoring', 'create_alert', 'Create an uptime or threshold alert'),
  ('monitoring.check_uptime', 'monitoring', 'check_uptime', 'Query the uptime status of a monitored endpoint'),
  ('monitoring.get_status_page', 'monitoring', 'get_status_page', 'Retrieve the current status page summary'),
  ('secrets.get', 'secrets', 'get', 'Retrieve a secret value by key'),
  ('secrets.set', 'secrets', 'set', 'Store or update a secret value'),
  ('secrets.list', 'secrets', 'list', 'List available secret keys in a namespace'),
  ('nlp.classify', 'nlp', 'classify', 'Classify text into predefined categories'),
  ('pdf.generate', 'pdf', 'generate', 'Generate a PDF from HTML, Markdown, or template'),
  ('timezone.convert', 'timezone', 'convert', 'Convert a datetime from one timezone to another'),
  ('timezone.get_info', 'timezone', 'get_info', 'Get timezone details, UTC offset, and DST status for a zone'),
  ('timezone.list', 'timezone', 'list', 'List all IANA timezone identifiers'),
  ('qr.generate', 'qr', 'generate', 'Generate a QR code image from a URL or text payload'),
  ('qr.decode', 'qr', 'decode', 'Decode a QR code image to extract its payload'),
  ('unit.convert', 'unit', 'convert', 'Convert a value between compatible units (length, weight, temp, etc.)'),
  ('unit.list_categories', 'unit', 'list_categories', 'List available unit categories and unit names'),
  ('unit.parse', 'unit', 'parse', 'Parse a human-readable measurement string into value + unit'),
  ('cache.get', 'cache', 'get', 'Read a value from a key-value cache'),
  ('cache.set', 'cache', 'set', 'Write a key-value pair to a cache with optional TTL'),
  ('cache.delete', 'cache', 'delete', 'Delete one or more keys from a cache'),
  ('network.whois', 'network', 'whois', 'Look up WHOIS registration data for a domain or IP'),
  ('network.dns_lookup', 'network', 'dns_lookup', 'Resolve DNS records for a domain'),
  ('network.ip_check', 'network', 'ip_check', 'Validate and classify an IP address'),
  ('network.ping', 'network', 'ping', 'Check reachability / uptime of a host or URL'),
  ('network.ssl_check', 'network', 'ssl_check', 'Inspect TLS/SSL certificate details for a domain'),
  ('embed.text', 'embed', 'text', 'Generate a vector embedding for a text string'),
  ('embed.batch', 'embed', 'batch', 'Generate embeddings for multiple inputs in one call'),
  ('embed.similarity', 'embed', 'similarity', 'Compute similarity score between two embeddings'),
  ('ratelimit.check', 'ratelimit', 'check', 'Check whether a key is within its rate limit'),
  ('ratelimit.increment', 'ratelimit', 'increment', 'Increment a counter and return remaining quota'),
  ('ratelimit.reset', 'ratelimit', 'reset', 'Reset a rate-limit counter for a given key'),
  ('audit.log', 'audit', 'log', 'Write a structured audit event to a durable log'),
  ('audit.query', 'audit', 'query', 'Query audit logs with filters (user, action, time)'),
  ('audit.export', 'audit', 'export', 'Export audit log entries as CSV or JSON'),
  ('ecommerce.search_products', 'ecommerce', 'search_products', 'Search a product catalog by query or filters'),
  ('ecommerce.get_product', 'ecommerce', 'get_product', 'Fetch details for a single product by ID or handle'),
  ('ecommerce.create_order', 'ecommerce', 'create_order', 'Place an order in a store or marketplace'),
  ('market.get_quote', 'market', 'get_quote', 'Get real-time or delayed quote for a stock or asset'),
  ('market.get_history', 'market', 'get_history', 'Fetch historical OHLCV price data for an asset'),
  ('market.search_symbols', 'market', 'search_symbols', 'Search for ticker symbols or financial instruments'),
  ('identity.verify', 'identity', 'verify', 'Verify a persons identity against document data'),
  ('identity.check_document', 'identity', 'check_document', 'Analyze and validate an ID document image'),
  ('identity.lookup', 'identity', 'lookup', 'Look up identity attributes from a phone or email'),
  ('chat.complete', 'chat', 'complete', 'Single-turn or multi-turn chat completion'),
  ('chat.stream', 'chat', 'stream', 'Streaming chat completion (SSE or chunked response)'),
  ('chat.function_call', 'chat', 'function_call', 'Chat completion with structured function/tool calling'),
  ('code.format', 'code', 'format', 'Auto-format source code according to a style guide'),
  ('code.lint', 'code', 'lint', 'Static analysis and lint check on source code'),
  ('code.analyze', 'code', 'analyze', 'Extract structure, symbols, or metrics from code'),
  ('seo.check', 'seo', 'check', 'Audit a URL for on-page SEO signals and issues'),
  ('seo.keywords', 'seo', 'keywords', 'Fetch keyword volume, difficulty, and ranking data'),
  ('export.csv', 'export', 'csv', 'Convert structured data to a CSV file or stream'),
  ('export.xlsx', 'export', 'xlsx', 'Convert structured data to an Excel (xlsx) workbook'),
  ('shipping.track', 'shipping', 'track', 'Track a package by carrier and tracking number'),
  ('shipping.get_rates', 'shipping', 'get_rates', 'Get shipping rates for a given package and destination'),
  ('shipping.create_label', 'shipping', 'create_label', 'Purchase and generate a shipping label'),
  ('receipt.parse', 'receipt', 'parse', 'Extract line items, totals, and metadata from a receipt or invoice'),
  ('receipt.extract_data', 'receipt', 'extract_data', 'Extract structured data fields from a scanned document'),
  ('agent.spawn', 'agent', 'spawn', 'Create and start a new autonomous agent run'),
  ('agent.get_status', 'agent', 'get_status', 'Check the status or output of a running agent'),
  ('agent.send_message', 'agent', 'send_message', 'Send a message or instruction to an active agent')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- STEP 2: Insert provider mappings into capability_services
-- Original table: capability_services
-- 0051-0063 targeted non-existent: provider_capability_mappings
-- ============================================================

INSERT INTO capability_services (capability_id, service_slug, credential_modes, auth_method, endpoint_pattern) VALUES
  ('translate.text', 'deepl', '{byo}', 'api_key', 'POST /v2/translate'),
  ('translate.text', 'google-translate', '{byo}', 'api_key', 'POST /language/translate/v2'),
  ('translate.text', 'aws-translate', '{byo}', 'api_key', 'POST / (AWS SDK)'),
  ('translate.text', 'libretranslate', '{byo}', 'api_key', 'POST /translate'),
  ('translate.detect_language', 'deepl', '{byo}', 'api_key', 'POST /v2/translate'),
  ('translate.detect_language', 'google-translate', '{byo}', 'api_key', 'POST /language/translate/v2/detect'),
  ('translate.detect_language', 'aws-translate', '{byo}', 'api_key', 'AWS Comprehend DetectDominantLanguage'),
  ('translate.batch', 'deepl', '{byo}', 'api_key', 'POST /v2/translate'),
  ('translate.batch', 'google-translate', '{byo}', 'api_key', 'POST /language/translate/v2'),
  ('translate.batch', 'aws-translate', '{byo}', 'api_key', 'StartTextTranslationJob'),
  ('image.resize', 'cloudinary', '{byo}', 'api_key', 'GET /image/upload/{transformations}/{public_id}'),
  ('image.resize', 'imgix', '{byo}', 'api_key', 'GET /{path}?w={w}&h={h}'),
  ('image.resize', 'imagekit', '{byo}', 'api_key', 'GET /{path}?tr=w-{w},h-{h}'),
  ('image.optimize', 'cloudinary', '{byo}', 'api_key', 'GET /image/upload/q_auto/{public_id}'),
  ('image.optimize', 'tinypng', '{byo}', 'api_key', 'POST /shrink'),
  ('image.optimize', 'imagekit', '{byo}', 'api_key', 'GET /{path}?tr=q-auto'),
  ('image.analyze', 'google-vision', '{byo}', 'api_key', 'POST /v1/images:annotate'),
  ('image.analyze', 'aws-rekognition', '{byo}', 'api_key', 'DetectLabels (AWS SDK)'),
  ('image.analyze', 'cloudinary', '{byo}', 'api_key', 'GET /image/upload/e_art/{public_id}'),
  ('currency.convert', 'exchangerate-api', '{byo}', 'api_key', 'GET /v6/{key}/pair/{from}/{to}/{amount}'),
  ('currency.convert', 'openexchangerates', '{byo}', 'api_key', 'GET /api/convert/{amount}/{from}/{to}'),
  ('currency.convert', 'fixer', '{byo}', 'api_key', 'GET /convert'),
  ('currency.get_rates', 'exchangerate-api', '{byo}', 'api_key', 'GET /v6/{key}/latest/{base}'),
  ('currency.get_rates', 'openexchangerates', '{byo}', 'api_key', 'GET /api/latest.json'),
  ('currency.get_rates', 'fixer', '{byo}', 'api_key', 'GET /latest'),
  ('currency.get_rates', 'currencylayer', '{byo}', 'api_key', 'GET /live'),
  ('maps.geocode', 'google-maps', '{byo}', 'api_key', 'GET /maps/api/geocode/json'),
  ('maps.geocode', 'mapbox', '{byo}', 'api_key', 'GET /geocoding/v5/mapbox.places/{query}.json'),
  ('maps.geocode', 'here-maps', '{byo}', 'api_key', 'GET /v1/geocode'),
  ('maps.geocode', 'opencage', '{byo}', 'api_key', 'GET /geocode/v1/json'),
  ('maps.directions', 'google-maps', '{byo}', 'api_key', 'GET /maps/api/directions/json'),
  ('maps.directions', 'mapbox', '{byo}', 'api_key', 'GET /directions/v5/mapbox/{profile}/{coordinates}'),
  ('maps.directions', 'here-maps', '{byo}', 'api_key', 'GET /v8/routes'),
  ('nlp.extract_entities', 'cohere', '{byo}', 'api_key', 'POST /v1/classify'),
  ('nlp.extract_entities', 'google-nlp', '{byo}', 'api_key', 'POST /v1/documents:analyzeEntities'),
  ('nlp.extract_entities', 'aws-comprehend', '{byo}', 'api_key', 'DetectEntities (AWS SDK)'),
  ('nlp.extract_entities', 'huggingface', '{byo}', 'api_key', 'POST /models/{model}'),
  ('nlp.sentiment', 'cohere', '{byo}', 'api_key', 'POST /v1/classify'),
  ('nlp.sentiment', 'google-nlp', '{byo}', 'api_key', 'POST /v1/documents:analyzeSentiment'),
  ('nlp.sentiment', 'aws-comprehend', '{byo}', 'api_key', 'DetectSentiment (AWS SDK)'),
  ('nlp.sentiment', 'meaningcloud', '{byo}', 'api_key', 'POST /sentiment-2.1'),
  ('nlp.summarize', 'cohere', '{byo}', 'api_key', 'POST /v1/summarize'),
  ('nlp.summarize', 'huggingface', '{byo}', 'api_key', 'POST /models/facebook/bart-large-cnn'),
  ('nlp.summarize', 'openai', '{byo}', 'api_key', 'POST /v1/chat/completions'),
  ('pdf.convert', 'pdfco', '{byo}', 'api_key', 'POST /v1/pdf/convert/from/doc'),
  ('pdf.convert', 'ilovepdf', '{byo}', 'api_key', 'POST /v1/upload + process'),
  ('pdf.convert', 'pdf-services', '{byo}', 'api_key', 'POST /operation/createpdf'),
  ('pdf.convert', 'unstructured', '{byo,rhumb_managed}', 'api_key', 'POST /general/v0/general'),
  ('pdf.merge', 'pdfco', '{byo}', 'api_key', 'POST /v1/pdf/merge'),
  ('pdf.merge', 'ilovepdf', '{byo}', 'api_key', 'POST /v1/merge'),
  ('pdf.merge', 'pdf-services', '{byo}', 'api_key', 'POST /operation/combinepdf'),
  ('pdf.extract_text', 'pdfco', '{byo}', 'api_key', 'POST /v1/pdf/convert/to/text'),
  ('pdf.extract_text', 'pdf-services', '{byo}', 'api_key', 'POST /operation/extractpdf'),
  ('pdf.extract_text', 'unstructured', '{byo,rhumb_managed}', 'api_key', 'POST /general/v0/general'),
  ('file.convert', 'cloudconvert', '{byo}', 'api_key', 'POST /v2/jobs'),
  ('file.convert', 'zamzar', '{byo}', 'api_key', 'POST /v1/jobs'),
  ('file.convert', 'unstructured', '{byo,rhumb_managed}', 'api_key', 'POST /general/v0/general'),
  ('file.compress', 'cloudconvert', '{byo}', 'api_key', 'POST /v2/jobs (archive task)'),
  ('file.compress', 'zamzar', '{byo}', 'api_key', 'POST /v1/jobs'),
  ('barcode.generate', 'qr-server', '{byo}', 'none', 'GET /create-qr-code/?data={data}'),
  ('barcode.generate', 'goqr', '{byo}', 'none', 'GET /api/qr?data={data}'),
  ('barcode.generate', 'barcodeapi', '{byo}', 'api_key', 'POST /barcode/{type}/{data}'),
  ('barcode.scan', 'google-vision', '{byo}', 'api_key', 'POST /v1/images:annotate (DOCUMENT_TEXT_DETECTION)'),
  ('barcode.scan', 'aws-rekognition', '{byo}', 'api_key', 'DetectText (AWS SDK)'),
  ('phone.validate', 'twilio', '{byo}', 'api_key', 'GET /v2/PhoneNumbers/{number}'),
  ('phone.validate', 'numverify', '{byo}', 'api_key', 'GET /api/validate'),
  ('phone.validate', 'telesign', '{byo}', 'api_key', 'POST /v1/phoneid/standard/{number}'),
  ('phone.validate', 'vonage', '{byo}', 'api_key', 'GET /ni/basic/json'),
  ('phone.lookup', 'twilio', '{byo}', 'api_key', 'GET /v2/PhoneNumbers/{number}?Fields=carrier'),
  ('phone.lookup', 'numverify', '{byo}', 'api_key', 'GET /api/validate'),
  ('phone.lookup', 'vonage', '{byo}', 'api_key', 'GET /ni/advanced/json'),
  ('phone.send_otp', 'twilio', '{byo}', 'api_key', 'POST /v2/Services/{sid}/Verifications'),
  ('phone.send_otp', 'vonage', '{byo}', 'api_key', 'POST /verify/v2/verifications'),
  ('phone.send_otp', 'telesign', '{byo}', 'api_key', 'POST /v1/verify/sms'),
  ('calendar.create_event', 'google-calendar', '{byo}', 'oauth2', 'POST /calendar/v3/calendars/{calendarId}/events'),
  ('calendar.create_event', 'microsoft-calendar', '{byo}', 'oauth2', 'POST /v1.0/me/events'),
  ('calendar.create_event', 'nylas', '{byo}', 'api_key', 'POST /v3/grants/{id}/events'),
  ('calendar.create_event', 'cal-com', '{byo}', 'api_key', 'POST /v1/bookings'),
  ('calendar.check_availability', 'google-calendar', '{byo}', 'oauth2', 'POST /calendar/v3/freeBusy'),
  ('calendar.check_availability', 'microsoft-calendar', '{byo}', 'oauth2', 'POST /v1.0/me/calendar/getSchedule'),
  ('calendar.check_availability', 'nylas', '{byo}', 'api_key', 'GET /v3/grants/{id}/events'),
  ('calendar.check_availability', 'cal-com', '{byo}', 'api_key', 'GET /v1/availability'),
  ('url.shorten', 'bitly', '{byo}', 'api_key', 'POST /v4/shorten'),
  ('url.shorten', 'tinyurl', '{byo}', 'api_key', 'POST /api/v1/create'),
  ('url.shorten', 'rebrandly', '{byo}', 'api_key', 'POST /v1/links'),
  ('url.shorten', 'dub', '{byo}', 'api_key', 'POST /api/v1/links'),
  ('url.expand', 'bitly', '{byo}', 'api_key', 'GET /v4/bitlinks/{id}'),
  ('url.expand', 'rebrandly', '{byo}', 'api_key', 'GET /v1/links/{id}'),
  ('social.get_profile', 'twitter', '{byo}', 'oauth2', 'GET /2/users/by/username/{username}'),
  ('social.get_profile', 'linkedin', '{byo}', 'oauth2', 'GET /v2/me'),
  ('social.get_profile', 'github', '{byo}', 'api_key', 'GET /users/{username}'),
  ('social.post', 'twitter', '{byo}', 'oauth2', 'POST /2/tweets'),
  ('social.post', 'linkedin', '{byo}', 'oauth2', 'POST /v2/ugcPosts'),
  ('social.post', 'buffer', '{byo}', 'api_key', 'POST /1/updates/create.json'),
  ('social.search', 'twitter', '{byo}', 'oauth2', 'GET /2/tweets/search/recent'),
  ('social.search', 'reddit', '{byo}', 'oauth2', 'GET /search.json'),
  ('social.search', 'github', '{byo}', 'api_key', 'GET /search/repositories'),
  ('weather.current', 'openweather', '{byo}', 'api_key', 'GET /data/2.5/weather'),
  ('weather.current', 'weatherapi', '{byo}', 'api_key', 'GET /v1/current.json'),
  ('weather.current', 'tomorrow-io', '{byo}', 'api_key', 'GET /v4/weather/realtime'),
  ('weather.current', 'open-meteo', '{byo}', 'none', 'GET /v1/forecast'),
  ('weather.forecast', 'openweather', '{byo}', 'api_key', 'GET /data/2.5/forecast'),
  ('weather.forecast', 'weatherapi', '{byo}', 'api_key', 'GET /v1/forecast.json'),
  ('weather.forecast', 'tomorrow-io', '{byo}', 'api_key', 'GET /v4/weather/forecast'),
  ('weather.forecast', 'open-meteo', '{byo}', 'none', 'GET /v1/forecast'),
  ('weather.historical', 'open-meteo', '{byo}', 'none', 'GET /v1/archive'),
  ('weather.historical', 'openweather', '{byo}', 'api_key', 'GET /data/3.0/onecall/timemachine'),
  ('weather.historical', 'weatherapi', '{byo}', 'api_key', 'GET /v1/history.json'),
  ('tax.calculate', 'taxjar', '{byo}', 'api_key', 'POST /v2/taxes'),
  ('tax.calculate', 'avatax', '{byo}', 'api_key', 'POST /api/v2/transactions/create'),
  ('tax.calculate', 'stripe-tax', '{byo}', 'api_key', 'Stripe Tax calculation'),
  ('tax.validate_vat', 'vatcheckapi', '{byo}', 'api_key', 'GET /vatcheck/{vat}'),
  ('tax.validate_vat', 'abstractapi', '{byo}', 'api_key', 'GET /?api_key={key}&vat_number={vat}'),
  ('tax.validate_vat', 'taxjar', '{byo}', 'api_key', 'GET /v2/validations'),
  ('dns.lookup', 'cloudflare-dns', '{byo}', 'none', 'GET /dns-query?name={domain}&type={type}'),
  ('dns.lookup', 'google-dns', '{byo}', 'none', 'GET /resolve?name={domain}&type={type}'),
  ('dns.lookup', 'abstractapi', '{byo}', 'api_key', 'GET /?api_key={key}&domain={domain}'),
  ('dns.whois', 'whoisxml', '{byo}', 'api_key', 'GET /whoisserver/WhoisService'),
  ('dns.whois', 'abstractapi', '{byo}', 'api_key', 'GET /api/whois'),
  ('dns.whois', 'domainr', '{byo}', 'api_key', 'GET /v2/status'),
  ('crypto.get_price', 'coingecko', '{byo}', 'api_key', 'GET /api/v3/simple/price'),
  ('crypto.get_price', 'coinbase', '{byo}', 'none', 'GET /v2/prices/{pair}/spot'),
  ('crypto.get_price', 'cryptocompare', '{byo}', 'api_key', 'GET /data/price'),
  ('crypto.get_rates', 'coingecko', '{byo}', 'api_key', 'GET /api/v3/simple/price'),
  ('crypto.get_rates', 'cryptocompare', '{byo}', 'api_key', 'GET /data/pricemultifull'),
  ('crypto.get_rates', 'coinbase', '{byo}', 'none', 'GET /v2/exchange-rates'),
  ('crypto.verify_address', 'blockcypher', '{byo}', 'api_key', 'GET /v1/{coin}/{chain}/addrs/{address}'),
  ('crypto.verify_address', 'chaingateway', '{byo}', 'api_key', 'POST /v2/address/validate'),
  ('validate.email', 'zerobounce', '{byo}', 'api_key', 'GET /v2/validate'),
  ('validate.email', 'hunter', '{byo}', 'api_key', 'GET /v2/email-verifier'),
  ('validate.email', 'kickbox', '{byo}', 'api_key', 'GET /v2/verify'),
  ('validate.email', 'millionverifier', '{byo}', 'api_key', 'GET /api/v3/verify'),
  ('validate.address', 'google-maps', '{byo}', 'api_key', 'POST /v1:validateAddress'),
  ('validate.address', 'smartystreets', '{byo}', 'api_key', 'GET /street-address'),
  ('validate.address', 'lob', '{byo}', 'api_key', 'POST /v1/us_verifications'),
  ('validate.address', 'here-maps', '{byo}', 'api_key', 'GET /v1/validate'),
  ('validate.vat', 'vatcheckapi', '{byo}', 'api_key', 'GET /api/v2/vatcheck'),
  ('validate.vat', 'abstractapi', '{byo}', 'api_key', 'GET /vat/v1/validate'),
  ('validate.vat', 'stripe-tax', '{byo}', 'api_key', 'POST /v1/tax/calculations'),
  ('video.transcode', 'cloudinary', '{byo}', 'api_key', 'POST /video/upload'),
  ('video.transcode', 'mux', '{byo}', 'api_key', 'POST /video/v1/assets'),
  ('video.transcode', 'cloudconvert', '{byo}', 'api_key', 'POST /v2/jobs'),
  ('video.thumbnail', 'cloudinary', '{byo}', 'api_key', 'GET /video/upload/so_{offset}/{id}'),
  ('video.thumbnail', 'mux', '{byo}', 'api_key', 'GET /video/v1/assets/{id}/images'),
  ('video.thumbnail', 'api.video', '{byo}', 'api_key', 'GET /videos/{id}/thumbnails'),
  ('video.subtitle', 'deepgram', '{byo,rhumb_managed}', 'api_key', 'POST /v1/listen?diarize=true'),
  ('video.subtitle', 'rev-ai', '{byo}', 'api_key', 'POST /speechtotext/v1/jobs'),
  ('video.subtitle', 'assemblyai', '{byo}', 'api_key', 'POST /v2/transcript'),
  ('notification.push', 'onesignal', '{byo}', 'api_key', 'POST /api/v1/notifications'),
  ('notification.push', 'expo', '{byo}', 'api_key', 'POST /--/api/v2/push/send'),
  ('notification.push', 'firebase', '{byo}', 'api_key', 'POST /v1/projects/{id}/messages:send'),
  ('notification.push', 'pusher', '{byo}', 'api_key', 'POST /apps/{id}/events'),
  ('notification.in_app', 'onesignal', '{byo}', 'api_key', 'POST /api/v1/notifications'),
  ('notification.in_app', 'novu', '{byo}', 'api_key', 'POST /v1/events/trigger'),
  ('notification.in_app', 'courier', '{byo}', 'api_key', 'POST /send'),
  ('spreadsheet.read', 'google-sheets', '{byo}', 'oauth2', 'GET /v4/spreadsheets/{id}/values/{range}'),
  ('spreadsheet.read', 'airtable', '{byo}', 'api_key', 'GET /v0/{base}/{table}'),
  ('spreadsheet.read', 'smartsheet', '{byo}', 'api_key', 'GET /sheets/{id}/rows'),
  ('spreadsheet.write', 'google-sheets', '{byo}', 'oauth2', 'PUT /v4/spreadsheets/{id}/values/{range}'),
  ('spreadsheet.write', 'airtable', '{byo}', 'api_key', 'POST /v0/{base}/{table}'),
  ('spreadsheet.write', 'smartsheet', '{byo}', 'api_key', 'POST /sheets/{id}/rows'),
  ('esign.create_request', 'docusign', '{byo}', 'oauth2', 'POST /v2.1/accounts/{id}/envelopes'),
  ('esign.create_request', 'hellosign', '{byo}', 'api_key', 'POST /v3/signature_request/send'),
  ('esign.create_request', 'pandadoc', '{byo}', 'api_key', 'POST /public/v1/documents'),
  ('esign.create_request', 'signnow', '{byo}', 'oauth2', 'POST /document'),
  ('esign.get_status', 'docusign', '{byo}', 'oauth2', 'GET /v2.1/accounts/{id}/envelopes/{envelopeId}'),
  ('esign.get_status', 'hellosign', '{byo}', 'api_key', 'GET /v3/signature_request/{id}'),
  ('esign.get_status', 'pandadoc', '{byo}', 'api_key', 'GET /public/v1/documents/{id}'),
  ('workflow.trigger', 'zapier', '{byo}', 'api_key', 'POST /hooks/catch/{hook_id}/'),
  ('workflow.trigger', 'make', '{byo}', 'api_key', 'POST /api/v2/scenarios/{id}/run'),
  ('workflow.trigger', 'n8n', '{byo}', 'api_key', 'POST /webhook/{path}'),
  ('workflow.trigger', 'pipedream', '{byo}', 'api_key', 'POST /workflows/{id}/events'),
  ('workflow.create', 'zapier', '{byo}', 'api_key', 'POST /v1/zaps'),
  ('workflow.create', 'make', '{byo}', 'api_key', 'POST /api/v2/scenarios'),
  ('workflow.create', 'pipedream', '{byo}', 'api_key', 'POST /v1/workflows'),
  ('monitoring.create_alert', 'pagerduty', '{byo}', 'api_key', 'POST /services'),
  ('monitoring.create_alert', 'uptimerobot', '{byo}', 'api_key', 'POST /v2/newMonitor'),
  ('monitoring.create_alert', 'betterstack', '{byo,rhumb_managed}', 'api_key', 'POST /api/v2/monitors'),
  ('monitoring.create_alert', 'freshstatus', '{byo}', 'api_key', 'POST /v2/monitors'),
  ('monitoring.check_uptime', 'uptimerobot', '{byo}', 'api_key', 'POST /v2/getMonitors'),
  ('monitoring.check_uptime', 'betterstack', '{byo,rhumb_managed}', 'api_key', 'GET /api/v2/monitors'),
  ('monitoring.check_uptime', 'freshstatus', '{byo}', 'api_key', 'GET /v2/monitors/{id}'),
  ('monitoring.check_uptime', 'statuscake', '{byo}', 'api_key', 'GET /v1/uptime'),
  ('monitoring.get_status_page', 'statuspage-io', '{byo}', 'api_key', 'GET /api/v2/summary.json'),
  ('monitoring.get_status_page', 'betterstack', '{byo,rhumb_managed}', 'api_key', 'GET /api/v2/status-pages'),
  ('monitoring.get_status_page', 'freshstatus', '{byo}', 'api_key', 'GET /v2/services'),
  ('secrets.get', 'doppler', '{byo}', 'api_key', 'GET /v3/configs/config/secret'),
  ('secrets.get', 'hashicorp-vault', '{byo}', 'api_key', 'GET /v1/{mount}/data/{path}'),
  ('secrets.get', 'aws-secrets-manager', '{byo}', 'api_key', 'GetSecretValue (AWS SDK)'),
  ('secrets.get', 'infisical', '{byo}', 'api_key', 'GET /api/v3/secrets/raw/{secretName}'),
  ('secrets.set', 'doppler', '{byo}', 'api_key', 'POST /v3/configs/config/secrets'),
  ('secrets.set', 'hashicorp-vault', '{byo}', 'api_key', 'POST /v1/{mount}/data/{path}'),
  ('secrets.set', 'aws-secrets-manager', '{byo}', 'api_key', 'PutSecretValue / CreateSecret (AWS SDK)'),
  ('secrets.set', 'infisical', '{byo}', 'api_key', 'POST /api/v3/secrets/raw/{secretName}'),
  ('secrets.list', 'doppler', '{byo}', 'api_key', 'GET /v3/configs/config/secrets'),
  ('secrets.list', 'hashicorp-vault', '{byo}', 'api_key', 'LIST /v1/{mount}/metadata/{path}'),
  ('secrets.list', 'infisical', '{byo}', 'api_key', 'GET /api/v3/secrets/raw'),
  ('nlp.sentiment', 'huggingface', '{byo}', 'api_key', 'POST /models/{model}'),
  ('nlp.classify', 'cohere', '{byo}', 'api_key', 'POST /v1/classify'),
  ('nlp.classify', 'aws-comprehend', '{byo}', 'api_key', 'ClassifyDocument (AWS SDK)'),
  ('nlp.classify', 'huggingface', '{byo}', 'api_key', 'POST /models/{model}'),
  ('pdf.generate', 'pdfco', '{byo}', 'api_key', 'POST /v1/pdf/convert/from/html'),
  ('pdf.generate', 'pdfmonkey', '{byo}', 'api_key', 'POST /v1/documents'),
  ('pdf.generate', 'ilovepdf', '{byo}', 'api_key', 'POST /v1/process'),
  ('timezone.convert', 'timezonedb', '{byo}', 'api_key', 'GET /v2.1/convert-time-zone'),
  ('timezone.convert', 'worldtimeapi', '{byo}', 'none', 'GET /api/timezone/{zone}'),
  ('timezone.convert', 'google-tz', '{byo}', 'api_key', 'GET /maps/api/timezone/json'),
  ('timezone.get_info', 'timezonedb', '{byo}', 'api_key', 'GET /v2.1/get-time-zone'),
  ('timezone.get_info', 'worldtimeapi', '{byo}', 'none', 'GET /api/timezone/{zone}'),
  ('timezone.get_info', 'ipinfo', '{byo,rhumb_managed}', 'bearer_token', 'GET /lite/{ip}'),
  ('timezone.list', 'worldtimeapi', '{byo}', 'none', 'GET /api/timezone'),
  ('timezone.list', 'timezonedb', '{byo}', 'api_key', 'GET /v2.1/list-time-zone'),
  ('qr.generate', 'qrserver', '{byo}', 'none', 'GET /v1/create-qr-code/?data={payload}'),
  ('qr.generate', 'qr-code-monkey', '{byo}', 'api_key', 'POST /api/qr'),
  ('qr.generate', 'goqr', '{byo}', 'none', 'GET /api/qr.png?data={payload}'),
  ('qr.decode', 'qrserver', '{byo}', 'none', 'POST /v1/read-qr-code/'),
  ('qr.decode', 'zxing', '{byo}', 'none', 'GET /w/decode?u={image_url}'),
  ('unit.convert', 'unitconverter-io', '{byo}', 'api_key', 'GET /api/convert'),
  ('unit.convert', 'convertapi', '{byo}', 'api_key', 'POST /convert/{from}/to/{to}'),
  ('unit.convert', 'free-unit-api', '{byo}', 'none', 'GET /convert'),
  ('unit.list_categories', 'unitconverter-io', '{byo}', 'api_key', 'GET /api/categories'),
  ('unit.parse', 'unitconverter-io', '{byo}', 'api_key', 'GET /api/parse'),
  ('cache.get', 'upstash', '{byo,rhumb_managed}', 'api_key', 'GET /get/{key}'),
  ('cache.get', 'redis-cloud', '{byo}', 'api_key', 'GET /get/{key}'),
  ('cache.get', 'momento', '{byo}', 'api_key', 'GET /cache/{cacheName}/{key}'),
  ('cache.set', 'upstash', '{byo,rhumb_managed}', 'api_key', 'POST /set/{key}/{value}'),
  ('cache.set', 'redis-cloud', '{byo}', 'api_key', 'POST /set'),
  ('cache.set', 'momento', '{byo}', 'api_key', 'PUT /cache/{cacheName}/{key}'),
  ('cache.delete', 'upstash', '{byo,rhumb_managed}', 'api_key', 'POST /del/{key}'),
  ('cache.delete', 'redis-cloud', '{byo}', 'api_key', 'POST /del'),
  ('cache.delete', 'momento', '{byo}', 'api_key', 'DELETE /cache/{cacheName}/{key}'),
  ('network.whois', 'whoisxml', '{byo}', 'api_key', 'GET /whoisserver/WhoisService'),
  ('network.whois', 'ipwhois', '{byo}', 'api_key', 'GET /json/{ip}'),
  ('network.whois', 'abstractapi', '{byo}', 'api_key', 'GET /whois'),
  ('network.dns_lookup', 'whoisxml', '{byo}', 'api_key', 'GET /dns-lookup'),
  ('network.dns_lookup', 'cloudflare', '{byo}', 'api_key', 'GET /dns-query?name={d}&type={t}'),
  ('network.dns_lookup', 'google-dns', '{byo}', 'api_key', 'GET /resolve?name={d}&type={t}'),
  ('network.ip_check', 'ipinfo', '{byo,rhumb_managed}', 'bearer_token', 'GET /lite/{ip}'),
  ('network.ip_check', 'abstractapi', '{byo}', 'api_key', 'GET /check'),
  ('network.ip_check', 'ipqualityscore', '{byo}', 'api_key', 'GET /json/{key}/{ip}'),
  ('network.ping', 'freshping', '{byo}', 'api_key', 'POST /checks'),
  ('network.ping', 'statuscake', '{byo}', 'api_key', 'POST /v1/uptime'),
  ('network.ping', 'hyperping', '{byo}', 'api_key', 'POST /monitors'),
  ('network.ssl_check', 'sslmate', '{byo}', 'api_key', 'GET /api/v1/cert/issuance'),
  ('network.ssl_check', 'whoisxml', '{byo}', 'api_key', 'GET /ssl-certificates/v1'),
  ('network.ssl_check', 'ssllabs', '{byo}', 'none', 'GET /analyze?host={domain}'),
  ('embed.text', 'openai', '{byo}', 'api_key', 'POST /v1/embeddings'),
  ('embed.text', 'cohere', '{byo}', 'api_key', 'POST /v1/embed'),
  ('embed.text', 'huggingface', '{byo}', 'api_key', 'POST /models/{model}'),
  ('embed.text', 'google-ai', '{byo}', 'api_key', 'POST /v1beta/models/{m}:embedContent'),
  ('embed.batch', 'openai', '{byo}', 'api_key', 'POST /v1/embeddings'),
  ('embed.batch', 'cohere', '{byo}', 'api_key', 'POST /v1/embed'),
  ('embed.batch', 'huggingface', '{byo}', 'api_key', 'POST /models/{model}'),
  ('embed.similarity', 'cohere', '{byo}', 'api_key', 'POST /v1/rerank'),
  ('embed.similarity', 'openai', '{byo}', 'api_key', 'POST /v1/embeddings'),
  ('ratelimit.check', 'upstash', '{byo,rhumb_managed}', 'api_key', 'POST /rl/limit'),
  ('ratelimit.check', 'redis-cloud', '{byo}', 'api_key', 'Redis INCR / TTL pattern'),
  ('ratelimit.check', 'momento', '{byo}', 'api_key', 'POST /cache/{name}/{key}'),
  ('ratelimit.increment', 'upstash', '{byo,rhumb_managed}', 'api_key', 'POST /rl/limit'),
  ('ratelimit.increment', 'redis-cloud', '{byo}', 'api_key', 'Redis INCR + EXPIRE'),
  ('ratelimit.increment', 'momento', '{byo}', 'api_key', 'POST /cache/{name}/{key}'),
  ('ratelimit.reset', 'upstash', '{byo,rhumb_managed}', 'api_key', 'POST /rl/reset'),
  ('ratelimit.reset', 'redis-cloud', '{byo}', 'api_key', 'Redis DEL {key}'),
  ('audit.log', 'axiom', '{byo}', 'api_key', 'POST /v1/datasets/{dataset}/ingest'),
  ('audit.log', 'datadog', '{byo}', 'api_key', 'POST /api/v2/logs'),
  ('audit.log', 'papertrail', '{byo}', 'api_key', 'UDP syslog / HTTP'),
  ('audit.log', 'workos', '{byo}', 'api_key', 'POST /events'),
  ('audit.query', 'axiom', '{byo}', 'api_key', 'POST /v1/datasets/{dataset}/query'),
  ('audit.query', 'datadog', '{byo}', 'api_key', 'GET /api/v2/logs/events'),
  ('audit.query', 'workos', '{byo}', 'api_key', 'GET /events'),
  ('audit.export', 'axiom', '{byo}', 'api_key', 'POST /v1/datasets/{dataset}/query'),
  ('audit.export', 'workos', '{byo}', 'api_key', 'GET /events?limit=100&...'),
  ('ecommerce.search_products', 'shopify', '{byo}', 'api_key', 'GET /admin/api/2024-01/products.json'),
  ('ecommerce.search_products', 'bigcommerce', '{byo}', 'api_key', 'GET /v3/catalog/products'),
  ('ecommerce.search_products', 'woocommerce', '{byo}', 'api_key', 'GET /wp-json/wc/v3/products'),
  ('ecommerce.search_products', 'algolia', '{byo,rhumb_managed}', 'api_key', 'POST /{index}/query'),
  ('ecommerce.get_product', 'shopify', '{byo}', 'api_key', 'GET /admin/api/2024-01/products/{id}.json'),
  ('ecommerce.get_product', 'bigcommerce', '{byo}', 'api_key', 'GET /v3/catalog/products/{id}'),
  ('ecommerce.get_product', 'woocommerce', '{byo}', 'api_key', 'GET /wp-json/wc/v3/products/{id}'),
  ('ecommerce.create_order', 'shopify', '{byo}', 'api_key', 'POST /admin/api/2024-01/orders.json'),
  ('ecommerce.create_order', 'bigcommerce', '{byo}', 'api_key', 'POST /v2/orders'),
  ('ecommerce.create_order', 'woocommerce', '{byo}', 'api_key', 'POST /wp-json/wc/v3/orders'),
  ('market.get_quote', 'alpaca', '{byo}', 'api_key', 'GET /v2/stocks/{symbol}/quotes/latest'),
  ('market.get_quote', 'polygon-io', '{byo}', 'api_key', 'GET /v2/last/trade/{symbol}'),
  ('market.get_quote', 'alpha-vantage', '{byo}', 'api_key', 'GET /query?function=GLOBAL_QUOTE'),
  ('market.get_quote', 'finnhub', '{byo}', 'api_key', 'GET /quote'),
  ('market.get_history', 'alpaca', '{byo}', 'api_key', 'GET /v2/stocks/{symbol}/bars'),
  ('market.get_history', 'polygon-io', '{byo}', 'api_key', 'GET /v2/aggs/ticker/{symbol}/range/{from}/{to}'),
  ('market.get_history', 'alpha-vantage', '{byo}', 'api_key', 'GET /query?function=TIME_SERIES_DAILY'),
  ('market.get_history', 'finnhub', '{byo}', 'api_key', 'GET /stock/candle'),
  ('market.search_symbols', 'polygon-io', '{byo}', 'api_key', 'GET /v3/reference/tickers'),
  ('market.search_symbols', 'alpha-vantage', '{byo}', 'api_key', 'GET /query?function=SYMBOL_SEARCH'),
  ('market.search_symbols', 'finnhub', '{byo}', 'api_key', 'GET /search'),
  ('identity.verify', 'persona', '{byo}', 'api_key', 'POST /api/v1/inquiries'),
  ('identity.verify', 'onfido', '{byo}', 'api_key', 'POST /v3.6/checks'),
  ('identity.verify', 'jumio', '{byo}', 'api_key', 'POST /api/v1/accounts'),
  ('identity.verify', 'stripe-identity', '{byo}', 'api_key', 'POST /v1/identity/verification_sessions'),
  ('identity.check_document', 'persona', '{byo}', 'api_key', 'POST /api/v1/inquiries'),
  ('identity.check_document', 'onfido', '{byo}', 'api_key', 'POST /v3.6/documents'),
  ('identity.check_document', 'jumio', '{byo}', 'api_key', 'POST /api/v1/accounts'),
  ('identity.lookup', 'ekata', '{byo}', 'api_key', 'GET /v2/identity_check'),
  ('identity.lookup', 'data-axle', '{byo}', 'api_key', 'POST /v1/match'),
  ('identity.lookup', 'ipinfo', '{byo,rhumb_managed}', 'bearer_token', 'GET /lite/{ip}'),
  ('chat.complete', 'openai', '{byo}', 'api_key', 'POST /v1/chat/completions'),
  ('chat.complete', 'anthropic', '{byo}', 'api_key', 'POST /v1/messages'),
  ('chat.complete', 'groq', '{byo}', 'api_key', 'POST /openai/v1/chat/completions'),
  ('chat.complete', 'mistral', '{byo}', 'api_key', 'POST /v1/chat/completions'),
  ('chat.complete', 'together-ai', '{byo}', 'api_key', 'POST /v1/chat/completions'),
  ('chat.stream', 'openai', '{byo}', 'api_key', 'POST /v1/chat/completions (stream=true)'),
  ('chat.stream', 'anthropic', '{byo}', 'api_key', 'POST /v1/messages (stream=true)'),
  ('chat.stream', 'groq', '{byo}', 'api_key', 'POST /openai/v1/chat/completions (stream=true)'),
  ('chat.stream', 'mistral', '{byo}', 'api_key', 'POST /v1/chat/completions (stream=true)'),
  ('chat.function_call', 'openai', '{byo}', 'api_key', 'POST /v1/chat/completions (tools=[...])'),
  ('chat.function_call', 'anthropic', '{byo}', 'api_key', 'POST /v1/messages (tools=[...])'),
  ('chat.function_call', 'groq', '{byo}', 'api_key', 'POST /openai/v1/chat/completions (tools=[...])'),
  ('chat.function_call', 'mistral', '{byo}', 'api_key', 'POST /v1/chat/completions (tools=[...])'),
  ('code.format', 'e2b', '{byo,rhumb_managed}', 'api_key', 'Sandbox exec: prettier/black/gofmt'),
  ('code.format', 'sourcegraph', '{byo}', 'api_key', 'POST /api/code-intelligence/format'),
  ('code.format', 'github-api', '{byo}', 'api_key', 'GitHub Actions runner'),
  ('code.lint', 'e2b', '{byo,rhumb_managed}', 'api_key', 'Sandbox exec: eslint/pylint/clippy'),
  ('code.lint', 'sonarcloud', '{byo}', 'api_key', 'POST /api/issues/search'),
  ('code.lint', 'deepsource', '{byo}', 'api_key', 'GraphQL API'),
  ('code.analyze', 'github-api', '{byo}', 'api_key', 'GET /repos/{owner}/{repo}/contents'),
  ('code.analyze', 'sourcegraph', '{byo}', 'api_key', 'POST /api/graphql'),
  ('code.analyze', 'sonarcloud', '{byo}', 'api_key', 'GET /api/measures/component'),
  ('seo.check', 'dataforseo', '{byo}', 'basic_auth', 'POST /v3/on_page/task_post'),
  ('seo.check', 'semrush', '{byo}', 'api_key', 'GET /reports/analytics/backlinks/'),
  ('seo.check', 'moz', '{byo}', 'api_key', 'POST /v2/url_metrics'),
  ('seo.keywords', 'dataforseo', '{byo}', 'basic_auth', 'POST /v3/keywords_data/google_ads/search_volume/task_post'),
  ('seo.keywords', 'semrush', '{byo}', 'api_key', 'GET /reports/analytics/phrase_all/'),
  ('seo.keywords', 'moz', '{byo}', 'api_key', 'POST /v2/keyword_difficulty'),
  ('export.csv', 'flatfile', '{byo}', 'api_key', 'POST /v1/workbooks'),
  ('export.csv', 'dataexporter', '{byo}', 'api_key', 'POST /api/v1/exports'),
  ('export.csv', 'airbyte', '{byo}', 'api_key', 'POST /v1/connections/sync'),
  ('export.xlsx', 'flatfile', '{byo}', 'api_key', 'POST /v1/workbooks'),
  ('export.xlsx', 'pdfmonkey', '{byo}', 'api_key', 'POST /api/v1/documents'),
  ('export.xlsx', 'dbtcloud', '{byo}', 'api_key', 'GET /api/v2/accounts/{id}/runs'),
  ('shipping.track', 'easypost', '{byo}', 'api_key', 'GET /v2/trackers/{id}'),
  ('shipping.track', 'shippo', '{byo}', 'api_key', 'GET /v1/tracks/{carrier}/{tracking_number}'),
  ('shipping.track', 'aftership', '{byo}', 'api_key', 'GET /v4/trackings/{slug}/{tracking_number}'),
  ('shipping.get_rates', 'easypost', '{byo}', 'api_key', 'POST /v2/shipments'),
  ('shipping.get_rates', 'shippo', '{byo}', 'api_key', 'POST /v1/shipments'),
  ('shipping.get_rates', 'shipstation', '{byo}', 'api_key', 'POST /shipments/getrates'),
  ('shipping.create_label', 'easypost', '{byo}', 'api_key', 'POST /v2/shipments/{id}/buy'),
  ('shipping.create_label', 'shippo', '{byo}', 'api_key', 'POST /v1/transactions'),
  ('shipping.create_label', 'shipstation', '{byo}', 'api_key', 'POST /orders/createlabelfororder'),
  ('receipt.parse', 'mindee', '{byo}', 'api_key', 'POST /v1/products/mindee/expense_receipts/v5/predict'),
  ('receipt.parse', 'veryfi', '{byo}', 'api_key', 'POST /api/v8/partner/{client_id}/documents/'),
  ('receipt.parse', 'unstructured', '{byo,rhumb_managed}', 'api_key', 'POST /general/v0/general'),
  ('receipt.extract_data', 'mindee', '{byo}', 'api_key', 'POST /v1/products/mindee/financial_document/v1/predict'),
  ('receipt.extract_data', 'aws-textract', '{byo}', 'api_key', 'DetectDocumentText / AnalyzeExpense (AWS SDK)'),
  ('agent.spawn', 'e2b', '{byo,rhumb_managed}', 'api_key', 'POST /sandboxes'),
  ('agent.spawn', 'modal', '{byo}', 'api_key', 'POST /v1/runs'),
  ('agent.spawn', 'inngest', '{byo}', 'api_key', 'POST /e/{event_key}'),
  ('agent.get_status', 'e2b', '{byo,rhumb_managed}', 'api_key', 'GET /sandboxes/{id}'),
  ('agent.get_status', 'modal', '{byo}', 'api_key', 'GET /v1/runs/{id}'),
  ('agent.get_status', 'inngest', '{byo}', 'api_key', 'GET /v1/runs/{run_id}'),
  ('agent.send_message', 'inngest', '{byo}', 'api_key', 'POST /e/{event_key}'),
  ('agent.send_message', 'temporal', '{byo}', 'api_key', 'POST /api/v1/namespaces/{ns}/workflows/{id}/signal'),
  ('network.dns_lookup', 'ipinfo', '{byo,rhumb_managed}', 'bearer_token', 'GET /{ip}/json'),
  ('network.whois', 'ipinfo', '{byo,rhumb_managed}', 'bearer_token', 'GET /{ip}/json')
ON CONFLICT (capability_id, service_slug) DO UPDATE SET
  credential_modes = EXCLUDED.credential_modes,
  auth_method = EXCLUDED.auth_method,
  endpoint_pattern = EXCLUDED.endpoint_pattern,
  updated_at = now();

-- ============================================================
-- Summary: 114 capabilities, 361 mappings reconciled
-- ============================================================

COMMIT;
