-- Migration 0085: Schema reconciliation for migrations 0064-0081
-- These migrations used wrong column names for both tables:
--   capabilities: used (id, name, domain, description, input_schema, output_schema)
--                 real: (id, domain, action, description, input_hint, outcome)
--   capability_services: used (capability_id, provider, tier, cost_per_call, quality_score, is_top_provider)
--                       real: (capability_id, service_slug, credential_modes, auth_method, endpoint_pattern, cost_per_call)
--
-- Applied to production via Supabase REST API on 2026-03-22
-- Author: Helm (rhumb-access)
--
-- Source: 181 capabilities, 629 mappings from 0064-0081
-- Production DB after: 419 capabilities, 1394 mappings, 64 execution configs

-- This migration was applied directly via PostgREST. The SQL below is for reference.
-- See the Python extraction script in the git history for the transformation logic.

BEGIN;

INSERT INTO capabilities (id, domain, action, description) VALUES
  ('hr.list_employees', 'hr', 'list_employees', 'List employees in an organization with optional filters'),
  ('hr.onboard_employee', 'hr', 'onboard_employee', 'Initiate onboarding workflow for a new employee'),
  ('hr.sync_roster', 'hr', 'sync_roster', 'Sync employee roster from HRIS to downstream systems'),
  ('survey.create', 'survey', 'create', 'Create a new survey with questions and settings'),
  ('survey.get_responses', 'survey', 'get_responses', 'Retrieve responses for a survey'),
  ('survey.get_results', 'survey', 'get_results', 'Get aggregated results and analytics for a survey'),
  ('localization.translate_keys', 'localization', 'translate_keys', 'Translate i18n key-value pairs into target locales'),
  ('localization.sync', 'localization', 'sync', 'Sync translation files with a localization platform'),
  ('localization.export', 'localization', 'export', 'Export translation files for a project in a specified format'),
  ('iam.provision_user', 'iam', 'provision_user', 'Provision a user account in a service via SCIM or native API'),
  ('iam.deprovision_user', 'iam', 'deprovision_user', 'Deprovision or suspend a user account'),
  ('knowledge.search', 'knowledge', 'search', 'Search a knowledge base for articles or documents matching a query'),
  ('knowledge.create_article', 'knowledge', 'create_article', 'Create or draft a new knowledge base article'),
  ('knowledge.get_article', 'knowledge', 'get_article', 'Retrieve a specific knowledge base article by ID or slug'),
  ('recommendation.get_items', 'recommendation', 'get_items', 'Get personalized item recommendations for a user'),
  ('recommendation.track_event', 'recommendation', 'track_event', 'Track a user interaction event to improve recommendations'),
  ('cms.get_page', 'cms', 'get_page', 'Retrieve a CMS page or entry by ID or slug'),
  ('cms.create_page', 'cms', 'create_page', 'Create a new page or content entry in a CMS'),
  ('cms.publish', 'cms', 'publish', 'Publish or schedule a CMS entry for public visibility'),
  ('reporting.generate', 'reporting', 'generate', 'Generate a report from a dataset or query with optional formatting'),
  ('reporting.schedule', 'reporting', 'schedule', 'Schedule a report for recurring automated delivery'),
  ('project.create_task', 'project', 'create_task', 'Create a task or issue in a project management system'),
  ('project.update_status', 'project', 'update_status', 'Update the status or state of a task or issue'),
  ('project.get_board', 'project', 'get_board', 'Retrieve the current state of a project board with tasks grouped by status'),
  ('appointment.get_availability', 'appointment', 'get_availability', 'Retrieve available time slots for a user or resource'),
  ('appointment.book', 'appointment', 'book', 'Book an appointment slot for an attendee'),
  ('appointment.cancel', 'appointment', 'cancel', 'Cancel an existing appointment booking'),
  ('telephony.make_call', 'telephony', 'make_call', 'Initiate an outbound voice call to a phone number'),
  ('telephony.get_recording', 'telephony', 'get_recording', 'Retrieve a call recording URL and metadata'),
  ('experiment.create', 'experiment', 'create', 'Create a new A/B test or feature experiment'),
  ('experiment.get_results', 'experiment', 'get_results', 'Retrieve statistical results for a running or completed experiment'),
  ('contract.create', 'contract', 'create', 'Create a contract or agreement document from a template or raw content'),
  ('contract.send', 'contract', 'send', 'Send a contract to one or more signers for electronic signature'),
  ('contract.get_status', 'contract', 'get_status', 'Get the current status and signer completion state of a contract'),
  ('inventory.check_stock', 'inventory', 'check_stock', 'Check current stock levels for one or more SKUs'),
  ('inventory.update_quantity', 'inventory', 'update_quantity', 'Update the quantity of a specific SKU at a location'),
  ('inventory.reserve', 'inventory', 'reserve', 'Reserve stock for a pending order to prevent overselling'),
  ('compliance.check', 'compliance', 'check', 'Run a compliance check against a framework (SOC2, ISO27001, GDPR, HIPAA)'),
  ('compliance.generate_report', 'compliance', 'generate_report', 'Generate a compliance evidence report for auditors or stakeholders'),
  ('referral.create_link', 'referral', 'create_link', 'Create a unique referral or affiliate tracking link for a participant'),
  ('referral.get_stats', 'referral', 'get_stats', 'Get conversion and reward stats for a referral participant or campaign'),
  ('ticket.create', 'ticket', 'create', 'Create a support ticket on behalf of a user or agent'),
  ('ticket.update', 'ticket', 'update', 'Update a support ticket status, priority, or assignee'),
  ('ticket.search', 'ticket', 'search', 'Search support tickets by query, status, or assignee'),
  ('subscription.create', 'subscription', 'create', 'Create a new subscription for a customer on a plan'),
  ('subscription.cancel', 'subscription', 'cancel', 'Cancel a subscription immediately or at period end'),
  ('subscription.get_status', 'subscription', 'get_status', 'Retrieve the current status and billing details of a subscription'),
  ('job.post_listing', 'job', 'post_listing', 'Post a job listing to a recruiting platform or job board'),
  ('job.get_candidates', 'job', 'get_candidates', 'Retrieve candidates who applied for a job listing'),
  ('feedback.collect_nps', 'feedback', 'collect_nps', 'Send an NPS or CSAT survey to a user or cohort'),
  ('feedback.get_responses', 'feedback', 'get_responses', 'Retrieve NPS or feedback survey responses for analysis'),
  ('chatbot.create', 'chatbot', 'create', 'Create or configure a chatbot widget or conversation flow'),
  ('chatbot.send_message', 'chatbot', 'send_message', 'Send a message to an active chat conversation'),
  ('chatbot.get_history', 'chatbot', 'get_history', 'Retrieve message history for a chat conversation'),
  ('loyalty.add_points', 'loyalty', 'add_points', 'Award loyalty points to a customer for a qualifying action'),
  ('loyalty.get_balance', 'loyalty', 'get_balance', 'Get a customer\'),
  ('loyalty.redeem', 'loyalty', 'redeem', 'Redeem loyalty points for a reward or discount'),
  ('marketplace.list_item', 'marketplace', 'list_item', 'Publish a product or service listing to a marketplace'),
  ('marketplace.search', 'marketplace', 'search', 'Search marketplace listings by keyword, category, or price range'),
  ('media.publish', 'media', 'publish', 'Publish or schedule a video or media asset to a hosting platform'),
  ('media.get_analytics', 'media', 'get_analytics', 'Retrieve view and engagement analytics for a published media asset'),
  ('wallet.create', 'wallet', 'create', 'Create a digital wallet or stored-value account for a customer'),
  ('wallet.get_balance', 'wallet', 'get_balance', 'Retrieve the current balance of a digital wallet'),
  ('wallet.send', 'wallet', 'send', 'Transfer funds from a wallet to another wallet or external account'),
  ('ml.predict', 'ml', 'predict', 'Run inference on a deployed ML model with input features'),
  ('ml.evaluate', 'ml', 'evaluate', 'Evaluate a model against a labeled dataset and return metrics'),
  ('cdn.purge', 'cdn', 'purge', 'Purge cached assets from a CDN edge by URL or tag'),
  ('cdn.get_stats', 'cdn', 'get_stats', 'Retrieve CDN traffic and cache hit rate analytics'),
  ('cdp.identify', 'cdp', 'identify', 'Identify and upsert a user profile in the customer data platform'),
  ('cdp.track', 'cdp', 'track', 'Track a named user event with properties for downstream destinations'),
  ('cdp.get_profile', 'cdp', 'get_profile', 'Retrieve a unified customer profile with merged traits and event history'),
  ('event_bus.publish', 'event_bus', 'publish', 'Publish an event or message to a topic or exchange'),
  ('event_bus.subscribe', 'event_bus', 'subscribe', 'Create a subscription to receive events from a topic'),
  ('event_bus.get_messages', 'event_bus', 'get_messages', 'Pull pending messages from a queue or subscription'),
  ('social_analytics.schedule_post', 'social_analytics', 'schedule_post', 'Schedule a social media post across one or more platforms'),
  ('social_analytics.get_analytics', 'social_analytics', 'get_analytics', 'Retrieve engagement analytics for social media posts or profiles'),
  ('contact.enrich', 'contact', 'enrich', 'Enrich a contact record with company, social, and demographic data'),
  ('contact.search', 'contact', 'search', 'Search for contacts matching filters like title, company, or location'),
  ('contact.update', 'contact', 'update', 'Update contact record fields in a CRM or contact database'),
  ('booking_resource.search_availability', 'booking_resource', 'search_availability', 'Search available resources (rooms, equipment, desks) for a time window'),
  ('booking_resource.reserve', 'booking_resource', 'reserve', 'Reserve a resource for a specified time window'),
  ('kyc.verify', 'kyc', 'verify', 'Submit a KYC verification request for a customer (AML/PEP screening, ID check)'),
  ('kyc.check_document', 'kyc', 'check_document', 'Submit a government-issued document for authenticity and data extraction'),
  ('workflow.create', 'workflow', 'create', 'Create or register a new automation workflow from a definition'),
  ('workflow.trigger', 'workflow', 'trigger', 'Manually trigger a workflow execution with optional input payload'),
  ('workflow.get_status', 'workflow', 'get_status', 'Get the current status and output of a workflow execution'),
  ('document_ai.extract_entities', 'document_ai', 'extract_entities', 'Extract structured entities (names, dates, amounts, line items) from a document'),
  ('document_ai.classify', 'document_ai', 'classify', 'Classify a document into a category (invoice, contract, ID, etc.)'),
  ('asset.upload', 'asset', 'upload', 'Upload a media asset (image, video, file) to a DAM or storage service'),
  ('asset.transform', 'asset', 'transform', 'Apply transformations (resize, crop, format convert, watermark) to an asset'),
  ('asset.get_url', 'asset', 'get_url', 'Get a signed or public delivery URL for a stored asset'),
  ('print.create_order', 'print', 'create_order', 'Place a print-on-demand order for a physical product'),
  ('print.get_status', 'print', 'get_status', 'Get the fulfillment and shipping status of a print-on-demand order'),
  ('iot.get_device_state', 'iot', 'get_device_state', 'Retrieve the current state and telemetry of an IoT device'),
  ('iot.send_command', 'iot', 'send_command', 'Send a command or desired state update to an IoT device'),
  ('database.query', 'database', 'query', 'Execute a read-only SQL query against a serverless database'),
  ('database.execute', 'database', 'execute', 'Execute a write SQL statement (INSERT, UPDATE, DELETE) against a serverless database'),
  ('database.get_schema', 'database', 'get_schema', 'Retrieve the table and column schema for a database connection'),
  ('storage_object.put', 'storage_object', 'put', 'Upload or overwrite an object in a storage bucket'),
  ('storage_object.get', 'storage_object', 'get', 'Retrieve an object or generate a pre-signed download URL'),
  ('storage_object.delete', 'storage_object', 'delete', 'Delete an object or list of objects from a storage bucket'),
  ('incident.create', 'incident', 'create', 'Create a new incident or alert in an on-call management platform'),
  ('incident.update', 'incident', 'update', 'Update the status, severity, or assignee of an existing incident'),
  ('incident.resolve', 'incident', 'resolve', 'Mark an incident as resolved and optionally add a post-mortem note'),
  ('pos.charge', 'pos', 'charge', 'Process a card-present payment at a point-of-sale terminal'),
  ('pos.get_transaction', 'pos', 'get_transaction', 'Retrieve details of a point-of-sale transaction by ID'),
  ('pos.refund', 'pos', 'refund', 'Issue a full or partial refund for a point-of-sale transaction'),
  ('gift_card.create', 'gift_card', 'create', 'Issue a new gift card with a specified balance'),
  ('gift_card.get_balance', 'gift_card', 'get_balance', 'Retrieve the remaining balance of a gift card by code or ID'),
  ('catalog.search_products', 'catalog', 'search_products', 'Search a product catalog by keyword, category, or attribute filters'),
  ('catalog.get_product', 'catalog', 'get_product', 'Retrieve full details for a specific product by ID or SKU'),
  ('realtime.publish', 'realtime', 'publish', 'Publish a message to a realtime channel for connected subscribers'),
  ('realtime.subscribe', 'realtime', 'subscribe', 'Create a server-side subscription to a realtime channel and register a webhook'),
  ('realtime.presence', 'realtime', 'presence', 'Get the list of currently connected members on a presence channel'),
  ('travel.search_flights', 'travel', 'search_flights', 'Search available flights between two airports for given dates'),
  ('travel.search_hotels', 'travel', 'search_hotels', 'Search available hotels at a destination for given dates'),
  ('payment_link.create', 'payment_link', 'create', 'Generate a shareable payment link for a specific amount or product'),
  ('payment_link.get', 'payment_link', 'get', 'Retrieve the status and payment details of a payment link'),
  ('resume.parse', 'resume', 'parse', 'Parse a resume document and extract structured candidate information'),
  ('resume.match', 'resume', 'match', 'Score a resume against a job description for candidate fit'),
  ('resume.score', 'resume', 'score', 'Score a resume for overall quality, completeness, and ATS compatibility'),
  ('fraud.score_transaction', 'fraud', 'score_transaction', 'Score a payment transaction for fraud risk before authorization'),
  ('fraud.flag_user', 'fraud', 'flag_user', 'Flag a user account for suspected fraud or abuse'),
  ('fraud.review', 'fraud', 'review', 'Retrieve fraud review queue items or the decision on a specific case'),
  ('video_conference.create_meeting', 'video_conference', 'create_meeting', 'Create a scheduled video meeting and return a join URL'),
  ('video_conference.get_recording', 'video_conference', 'get_recording', 'Retrieve the recording URL and metadata for a completed meeting'),
  ('review.request', 'review', 'request', 'Send a review request to a customer after a purchase or interaction'),
  ('review.get_summary', 'review', 'get_summary', 'Get aggregated review stats and recent reviews for a product or business'),
  ('legal.search_entity', 'legal', 'search_entity', 'Search for a company or legal entity by name or registration number'),
  ('legal.check_sanctions', 'legal', 'check_sanctions', 'Screen a person or entity against global sanctions and watchlists'),
  ('legal.get_filings', 'legal', 'get_filings', 'Retrieve regulatory filings or corporate documents for a legal entity'),
  ('lead.create', 'lead', 'create', 'Create a new sales lead in a CRM or marketing automation platform'),
  ('lead.score', 'lead', 'score', 'Score a lead based on firmographic and behavioral signals'),
  ('lead.assign', 'lead', 'assign', 'Assign a lead to a sales representative or round-robin queue'),
  ('quote.create', 'quote', 'create', 'Generate a sales quote or proposal document for a prospect'),
  ('quote.send', 'quote', 'send', 'Send a quote to the recipient for review and electronic acceptance'),
  ('quote.get_status', 'quote', 'get_status', 'Get the current status of a quote (viewed, accepted, declined, expired)'),
  ('waitlist.join', 'waitlist', 'join', 'Add a user to a waitlist and return their position'),
  ('waitlist.get_position', 'waitlist', 'get_position', 'Get a waitlist member\'),
  ('social_listening.search_mentions', 'social_listening', 'search_mentions', 'Search for brand mentions, keywords, or hashtags across social and web sources'),
  ('social_listening.get_alerts', 'social_listening', 'get_alerts', 'Retrieve active brand monitoring alert configurations and recent triggers'),
  ('affiliate.create_link', 'affiliate', 'create_link', 'Generate a trackable affiliate referral link for a partner'),
  ('affiliate.get_stats', 'affiliate', 'get_stats', 'Retrieve clicks, conversions, and revenue attribution for an affiliate partner'),
  ('affiliate.get_commissions', 'affiliate', 'get_commissions', 'List pending or paid commission payouts for an affiliate partner'),
  ('news.search', 'news', 'search', 'Search news articles by keyword, topic, or source'),
  ('news.get_headlines', 'news', 'get_headlines', 'Retrieve top headlines for a country, category, or source'),
  ('data_warehouse.query', 'data_warehouse', 'query', 'Execute an analytical SQL query against a data warehouse'),
  ('data_warehouse.run_job', 'data_warehouse', 'run_job', 'Submit an async transformation or export job and return a job handle'),
  ('certificate.issue', 'certificate', 'issue', 'Issue or renew a TLS/SSL certificate for one or more domains'),
  ('certificate.get_status', 'certificate', 'get_status', 'Check the current status and expiry of an issued certificate'),
  ('certificate.revoke', 'certificate', 'revoke', 'Revoke an issued TLS/SSL certificate'),
  ('accessibility.scan', 'accessibility', 'scan', 'Run an automated accessibility audit against a URL or HTML snippet'),
  ('accessibility.report', 'accessibility', 'report', 'Generate a formatted accessibility audit report for a URL'),
  ('load_test.run', 'load_test', 'run', 'Start a load test against a target URL with specified concurrency and duration'),
  ('load_test.get_results', 'load_test', 'get_results', 'Retrieve the results and performance metrics for a completed load test'),
  ('load_test.get_metrics', 'load_test', 'get_metrics', 'Stream time-series performance metrics for a running or completed load test'),
  ('sports.get_scores', 'sports', 'get_scores', 'Get live or final scores for games in a sport and league'),
  ('sports.get_schedule', 'sports', 'get_schedule', 'Retrieve the upcoming game schedule for a team or league'),
  ('sports.get_standings', 'sports', 'get_standings', 'Get current league standings or division rankings'),
  ('backup.create', 'backup', 'create', 'Trigger a backup job for a resource (database, volume, or storage bucket)'),
  ('backup.get_status', 'backup', 'get_status', 'Check the status and metadata of a backup job'),
  ('image_moderation.check_image', 'image_moderation', 'check_image', 'Scan an image for unsafe, explicit, or policy-violating content'),
  ('image_moderation.check_text', 'image_moderation', 'check_text', 'Scan a text string for toxic, hateful, or policy-violating content'),
  ('image_moderation.get_report', 'image_moderation', 'get_report', 'Retrieve a moderation report or audit log for a previous check'),
  ('domain_registration.search_availability', 'domain_registration', 'search_availability', 'Check whether one or more domain names are available for registration'),
  ('domain_registration.register', 'domain_registration', 'register', 'Register a domain name with contact and DNS details'),
  ('domain_registration.get_info', 'domain_registration', 'get_info', 'Get WHOIS and registration details for a domain'),
  ('address_verification.verify', 'address_verification', 'verify', 'Validate and standardize a postal address'),
  ('address_verification.autocomplete', 'address_verification', 'autocomplete', 'Suggest address completions as a user types'),
  ('fleet.track_vehicle', 'fleet', 'track_vehicle', 'Get real-time location and telemetry for a fleet vehicle'),
  ('fleet.get_location_history', 'fleet', 'get_location_history', 'Retrieve the location history and trip data for a fleet vehicle'),
  ('conversation_intelligence.analyze_call', 'conversation_intelligence', 'analyze_call', 'Submit a call recording for AI-powered conversation analysis'),
  ('conversation_intelligence.get_transcript', 'conversation_intelligence', 'get_transcript', 'Retrieve the full transcript and speaker diarization for an analyzed call'),
  ('conversation_intelligence.get_insights', 'conversation_intelligence', 'get_insights', 'Get AI-extracted insights from an analyzed call: topics, sentiment, next steps'),
  ('geofence.create', 'geofence', 'create', 'Create a geographic boundary that triggers events when entered or exited'),
  ('geofence.check', 'geofence', 'check', 'Check whether a coordinate is inside one or more active geofences'),
  ('geofence.list_events', 'geofence', 'list_events', 'List enter/exit events for a geofence within a time range'),
  ('package.search', 'package', 'search', 'Search a software package registry by name or keyword'),
  ('package.get_info', 'package', 'get_info', 'Retrieve metadata, version history, and dependencies for a package'),
  ('forecast.run', 'forecast', 'run', 'Submit a time-series dataset and run a demand or metric forecast'),
  ('forecast.get_results', 'forecast', 'get_results', 'Retrieve the completed forecast values and confidence intervals')
ON CONFLICT (id) DO NOTHING;

INSERT INTO capability_services (capability_id, service_slug, credential_modes, cost_per_call) VALUES
  ('hr.list_employees', 'bamboohr', '{byo}', 0.001),
  ('hr.list_employees', 'rippling', '{byo}', 0.001),
  ('hr.list_employees', 'gusto', '{byo}', 0.001),
  ('hr.list_employees', 'workday', '{byo}', 0.002),
  ('hr.onboard_employee', 'bamboohr', '{byo}', 0.005),
  ('hr.onboard_employee', 'rippling', '{byo}', 0.005),
  ('hr.onboard_employee', 'gusto', '{byo}', 0.005),
  ('hr.sync_roster', 'bamboohr', '{byo}', 0.002),
  ('hr.sync_roster', 'workday', '{byo}', 0.003),
  ('hr.sync_roster', 'namely', '{byo}', 0.002),
  ('survey.create', 'typeform', '{byo}', 0.003),
  ('survey.create', 'surveymonkey', '{byo}', 0.003),
  ('survey.create', 'tally', '{byo}', 0.002),
  ('survey.create', 'google-forms', '{byo}', 0.001),
  ('survey.get_responses', 'typeform', '{byo}', 0.002),
  ('survey.get_responses', 'surveymonkey', '{byo}', 0.002),
  ('survey.get_responses', 'tally', '{byo}', 0.001),
  ('survey.get_results', 'typeform', '{byo}', 0.003),
  ('survey.get_results', 'surveymonkey', '{byo}', 0.003),
  ('survey.get_results', 'delighted', '{byo}', 0.003),
  ('localization.translate_keys', 'lokalise', '{byo}', 0.005),
  ('localization.translate_keys', 'phrase', '{byo}', 0.005),
  ('localization.translate_keys', 'crowdin', '{byo}', 0.004),
  ('localization.sync', 'lokalise', '{byo}', 0.003),
  ('localization.sync', 'phrase', '{byo}', 0.003),
  ('localization.sync', 'crowdin', '{byo}', 0.003),
  ('localization.sync', 'transifex', '{byo}', 0.003),
  ('localization.export', 'lokalise', '{byo}', 0.002),
  ('localization.export', 'phrase', '{byo}', 0.002),
  ('localization.export', 'crowdin', '{byo}', 0.002),
  ('localization.export', 'transifex', '{byo}', 0.002),
  ('iam.provision_user', 'okta', '{byo}', 0.005),
  ('iam.provision_user', 'auth0', '{byo}', 0.004),
  ('iam.provision_user', 'workos', '{byo}', 0.004),
  ('iam.provision_user', 'jumpcloud', '{byo}', 0.003),
  ('iam.deprovision_user', 'okta', '{byo}', 0.005),
  ('iam.deprovision_user', 'auth0', '{byo}', 0.004),
  ('iam.deprovision_user', 'workos', '{byo}', 0.004),
  ('iam.deprovision_user', 'jumpcloud', '{byo}', 0.003),
  ('knowledge.search', 'confluence', '{byo}', 0.002),
  ('knowledge.search', 'notion', '{byo}', 0.002),
  ('knowledge.search', 'zendesk-guide', '{byo}', 0.002),
  ('knowledge.search', 'document360', '{byo}', 0.002),
  ('knowledge.create_article', 'confluence', '{byo}', 0.004),
  ('knowledge.create_article', 'notion', '{byo}', 0.003),
  ('knowledge.create_article', 'zendesk-guide', '{byo}', 0.003),
  ('knowledge.create_article', 'guru', '{byo}', 0.003),
  ('knowledge.get_article', 'confluence', '{byo}', 0.001),
  ('knowledge.get_article', 'notion', '{byo}', 0.001),
  ('knowledge.get_article', 'zendesk-guide', '{byo}', 0.001),
  ('knowledge.get_article', 'document360', '{byo}', 0.001),
  ('recommendation.get_items', 'recombee', '{byo}', 0.003),
  ('recommendation.get_items', 'aws-personalize', '{byo}', 0.004),
  ('recommendation.get_items', 'dynamic-yield', '{byo}', 0.005),
  ('recommendation.get_items', 'barilliance', '{byo}', 0.004),
  ('recommendation.track_event', 'recombee', '{byo}', 0.001),
  ('recommendation.track_event', 'aws-personalize', '{byo}', 0.001),
  ('recommendation.track_event', 'segment', '{byo}', 0.001),
  ('recommendation.track_event', 'dynamic-yield', '{byo}', 0.001),
  ('cms.get_page', 'contentful', '{byo}', 0.001),
  ('cms.get_page', 'sanity', '{byo}', 0.001),
  ('cms.get_page', 'prismic', '{byo}', 0.001),
  ('cms.get_page', 'strapi', '{byo}', 0.001),
  ('cms.create_page', 'contentful', '{byo}', 0.003),
  ('cms.create_page', 'sanity', '{byo}', 0.003),
  ('cms.create_page', 'prismic', '{byo}', 0.003),
  ('cms.create_page', 'ghost', '{byo}', 0.002),
  ('cms.publish', 'contentful', '{byo}', 0.002),
  ('cms.publish', 'sanity', '{byo}', 0.002),
  ('cms.publish', 'ghost', '{byo}', 0.002),
  ('cms.publish', 'prismic', '{byo}', 0.002),
  ('reporting.generate', 'metabase', '{byo}', 0.005),
  ('reporting.generate', 'looker', '{byo}', 0.008),
  ('reporting.generate', 'redash', '{byo}', 0.004),
  ('reporting.generate', 'retool', '{byo}', 0.006),
  ('reporting.schedule', 'metabase', '{byo}', 0.003),
  ('reporting.schedule', 'looker', '{byo}', 0.005),
  ('reporting.schedule', 'redash', '{byo}', 0.003),
  ('project.create_task', 'linear', '{byo}', 0.002),
  ('project.create_task', 'jira', '{byo}', 0.003),
  ('project.create_task', 'asana', '{byo}', 0.002),
  ('project.create_task', 'github', '{byo}', 0.001),
  ('project.update_status', 'linear', '{byo}', 0.002),
  ('project.update_status', 'jira', '{byo}', 0.003),
  ('project.update_status', 'asana', '{byo}', 0.002),
  ('project.update_status', 'trello', '{byo}', 0.001),
  ('project.get_board', 'linear', '{byo}', 0.002),
  ('project.get_board', 'jira', '{byo}', 0.003),
  ('project.get_board', 'asana', '{byo}', 0.002),
  ('project.get_board', 'trello', '{byo}', 0.001),
  ('appointment.get_availability', 'calendly', '{byo}', 0.002),
  ('appointment.get_availability', 'cal-com', '{byo}', 0.001),
  ('appointment.get_availability', 'acuity', '{byo}', 0.002),
  ('appointment.get_availability', 'savvycal', '{byo}', 0.002),
  ('appointment.book', 'calendly', '{byo}', 0.003),
  ('appointment.book', 'cal-com', '{byo}', 0.002),
  ('appointment.book', 'acuity', '{byo}', 0.003),
  ('appointment.cancel', 'calendly', '{byo}', 0.002),
  ('appointment.cancel', 'cal-com', '{byo}', 0.001),
  ('appointment.cancel', 'acuity', '{byo}', 0.002),
  ('telephony.make_call', 'twilio', '{byo}', 0.02),
  ('telephony.make_call', 'vonage', '{byo}', 0.018),
  ('telephony.make_call', 'plivo', '{byo}', 0.015),
  ('telephony.make_call', 'signalwire', '{byo}', 0.016),
  ('telephony.get_recording', 'twilio', '{byo}', 0.003),
  ('telephony.get_recording', 'vonage', '{byo}', 0.003),
  ('telephony.get_recording', 'plivo', '{byo}', 0.002),
  ('experiment.create', 'statsig', '{byo}', 0.003),
  ('experiment.create', 'optimizely', '{byo}', 0.005),
  ('experiment.create', 'launchdarkly', '{byo}', 0.004),
  ('experiment.create', 'growthbook', '{byo}', 0.002),
  ('experiment.get_results', 'statsig', '{byo}', 0.003),
  ('experiment.get_results', 'optimizely', '{byo}', 0.004),
  ('experiment.get_results', 'launchdarkly', '{byo}', 0.003),
  ('experiment.get_results', 'growthbook', '{byo}', 0.002),
  ('contract.create', 'docusign', '{byo}', 0.01),
  ('contract.create', 'pandadoc', '{byo}', 0.008),
  ('contract.create', 'hellosign', '{byo}', 0.007),
  ('contract.create', 'dropbox-sign', '{byo}', 0.007),
  ('contract.send', 'docusign', '{byo}', 0.015),
  ('contract.send', 'pandadoc', '{byo}', 0.012),
  ('contract.send', 'hellosign', '{byo}', 0.01),
  ('contract.send', 'dropbox-sign', '{byo}', 0.01),
  ('contract.get_status', 'docusign', '{byo}', 0.003),
  ('contract.get_status', 'pandadoc', '{byo}', 0.003),
  ('contract.get_status', 'hellosign', '{byo}', 0.002),
  ('contract.get_status', 'dropbox-sign', '{byo}', 0.002),
  ('inventory.check_stock', 'shopify', '{byo}', 0.002),
  ('inventory.check_stock', 'square', '{byo}', 0.002),
  ('inventory.check_stock', 'lightspeed', '{byo}', 0.002),
  ('inventory.check_stock', 'cin7', '{byo}', 0.003),
  ('inventory.update_quantity', 'shopify', '{byo}', 0.003),
  ('inventory.update_quantity', 'square', '{byo}', 0.003),
  ('inventory.update_quantity', 'cin7', '{byo}', 0.003),
  ('inventory.reserve', 'shopify', '{byo}', 0.004),
  ('inventory.reserve', 'square', '{byo}', 0.003),
  ('inventory.reserve', 'lightspeed', '{byo}', 0.003),
  ('compliance.check', 'vanta', '{byo}', 0.02),
  ('compliance.check', 'drata', '{byo}', 0.02),
  ('compliance.check', 'secureframe', '{byo}', 0.018),
  ('compliance.check', 'sprinto', '{byo}', 0.015),
  ('compliance.generate_report', 'vanta', '{byo}', 0.03),
  ('compliance.generate_report', 'drata', '{byo}', 0.03),
  ('compliance.generate_report', 'secureframe', '{byo}', 0.025),
  ('referral.create_link', 'rewardful', '{byo}', 0.003),
  ('referral.create_link', 'partnerstack', '{byo}', 0.004),
  ('referral.create_link', 'tapfiliate', '{byo}', 0.003),
  ('referral.create_link', 'referralhero', '{byo}', 0.003),
  ('referral.get_stats', 'rewardful', '{byo}', 0.002),
  ('referral.get_stats', 'partnerstack', '{byo}', 0.003),
  ('referral.get_stats', 'tapfiliate', '{byo}', 0.002),
  ('ticket.create', 'zendesk', '{byo}', 0.003),
  ('ticket.create', 'freshdesk', '{byo}', 0.002),
  ('ticket.create', 'intercom', '{byo}', 0.004),
  ('ticket.create', 'help-scout', '{byo}', 0.002),
  ('ticket.update', 'zendesk', '{byo}', 0.003),
  ('ticket.update', 'freshdesk', '{byo}', 0.002),
  ('ticket.update', 'intercom', '{byo}', 0.003),
  ('ticket.update', 'help-scout', '{byo}', 0.002),
  ('ticket.search', 'zendesk', '{byo}', 0.003),
  ('ticket.search', 'freshdesk', '{byo}', 0.002),
  ('ticket.search', 'intercom', '{byo}', 0.003),
  ('subscription.create', 'stripe', '{byo}', 0.005),
  ('subscription.create', 'chargebee', '{byo}', 0.006),
  ('subscription.create', 'recurly', '{byo}', 0.006),
  ('subscription.create', 'paddle', '{byo}', 0.005),
  ('subscription.cancel', 'stripe', '{byo}', 0.004),
  ('subscription.cancel', 'chargebee', '{byo}', 0.005),
  ('subscription.cancel', 'recurly', '{byo}', 0.005),
  ('subscription.cancel', 'paddle', '{byo}', 0.004),
  ('subscription.get_status', 'stripe', '{byo}', 0.002),
  ('subscription.get_status', 'chargebee', '{byo}', 0.003),
  ('subscription.get_status', 'recurly', '{byo}', 0.003),
  ('job.post_listing', 'greenhouse', '{byo}', 0.005),
  ('job.post_listing', 'lever', '{byo}', 0.005),
  ('job.post_listing', 'workable', '{byo}', 0.004),
  ('job.post_listing', 'breezyhr', '{byo}', 0.003),
  ('job.get_candidates', 'greenhouse', '{byo}', 0.004),
  ('job.get_candidates', 'lever', '{byo}', 0.004),
  ('job.get_candidates', 'workable', '{byo}', 0.003),
  ('job.get_candidates', 'breezyhr', '{byo}', 0.003),
  ('feedback.collect_nps', 'delighted', '{byo}', 0.004),
  ('feedback.collect_nps', 'hotjar', '{byo}', 0.003),
  ('feedback.collect_nps', 'medallia', '{byo}', 0.008),
  ('feedback.collect_nps', 'satismeter', '{byo}', 0.004),
  ('feedback.get_responses', 'delighted', '{byo}', 0.003),
  ('feedback.get_responses', 'hotjar', '{byo}', 0.003),
  ('feedback.get_responses', 'medallia', '{byo}', 0.006),
  ('chatbot.create', 'intercom', '{byo}', 0.01),
  ('chatbot.create', 'drift', '{byo}', 0.009),
  ('chatbot.create', 'tidio', '{byo}', 0.005),
  ('chatbot.create', 'crisp', '{byo}', 0.004),
  ('chatbot.send_message', 'intercom', '{byo}', 0.003),
  ('chatbot.send_message', 'drift', '{byo}', 0.003),
  ('chatbot.send_message', 'tidio', '{byo}', 0.002),
  ('chatbot.send_message', 'crisp', '{byo}', 0.002),
  ('chatbot.get_history', 'intercom', '{byo}', 0.002),
  ('chatbot.get_history', 'drift', '{byo}', 0.002),
  ('chatbot.get_history', 'tidio', '{byo}', 0.001),
  ('loyalty.add_points', 'loyaltylion', '{byo}', 0.004),
  ('loyalty.add_points', 'yotpo', '{byo}', 0.005),
  ('loyalty.add_points', 'stamp-me', '{byo}', 0.003),
  ('loyalty.add_points', 'smile-io', '{byo}', 0.004),
  ('loyalty.get_balance', 'loyaltylion', '{byo}', 0.002),
  ('loyalty.get_balance', 'yotpo', '{byo}', 0.002),
  ('loyalty.get_balance', 'smile-io', '{byo}', 0.002),
  ('loyalty.redeem', 'loyaltylion', '{byo}', 0.005),
  ('loyalty.redeem', 'yotpo', '{byo}', 0.006),
  ('loyalty.redeem', 'smile-io', '{byo}', 0.005),
  ('marketplace.list_item', 'shopify', '{byo}', 0.004),
  ('marketplace.list_item', 'ebay', '{byo}', 0.005),
  ('marketplace.list_item', 'etsy', '{byo}', 0.004),
  ('marketplace.list_item', 'woocommerce', '{byo}', 0.003),
  ('marketplace.search', 'shopify', '{byo}', 0.002),
  ('marketplace.search', 'ebay', '{byo}', 0.002),
  ('marketplace.search', 'etsy', '{byo}', 0.002),
  ('media.publish', 'mux', '{byo}', 0.01),
  ('media.publish', 'vimeo', '{byo}', 0.008),
  ('media.publish', 'wistia', '{byo}', 0.009),
  ('media.publish', 'youtube', '{byo}', 0.005),
  ('media.get_analytics', 'mux', '{byo}', 0.005),
  ('media.get_analytics', 'vimeo', '{byo}', 0.004),
  ('media.get_analytics', 'wistia', '{byo}', 0.004),
  ('media.get_analytics', 'youtube', '{byo}', 0.003),
  ('wallet.create', 'stripe', '{byo}', 0.005),
  ('wallet.create', 'marqeta', '{byo}', 0.008),
  ('wallet.create', 'circle', '{byo}', 0.006),
  ('wallet.get_balance', 'stripe', '{byo}', 0.002),
  ('wallet.get_balance', 'marqeta', '{byo}', 0.003),
  ('wallet.get_balance', 'circle', '{byo}', 0.002),
  ('wallet.get_balance', 'plaid', '{byo}', 0.004),
  ('wallet.send', 'stripe', '{byo}', 0.01),
  ('wallet.send', 'marqeta', '{byo}', 0.012),
  ('wallet.send', 'circle', '{byo}', 0.008),
  ('ml.predict', 'aws-sagemaker', '{byo}', 0.01),
  ('ml.predict', 'google-vertex', '{byo}', 0.01),
  ('ml.predict', 'huggingface', '{byo}', 0.005),
  ('ml.predict', 'replicate', '{byo}', 0.008),
  ('ml.evaluate', 'aws-sagemaker', '{byo}', 0.015),
  ('ml.evaluate', 'google-vertex', '{byo}', 0.015),
  ('ml.evaluate', 'huggingface', '{byo}', 0.01),
  ('cdn.purge', 'cloudflare', '{byo}', 0.003),
  ('cdn.purge', 'fastly', '{byo}', 0.004),
  ('cdn.purge', 'aws-cloudfront', '{byo}', 0.005),
  ('cdn.purge', 'bunny', '{byo}', 0.002),
  ('cdn.get_stats', 'cloudflare', '{byo}', 0.003),
  ('cdn.get_stats', 'fastly', '{byo}', 0.003),
  ('cdn.get_stats', 'aws-cloudfront', '{byo}', 0.004),
  ('cdp.identify', 'segment', '{byo}', 0.002),
  ('cdp.identify', 'rudderstack', '{byo}', 0.002),
  ('cdp.identify', 'mparticle', '{byo}', 0.003),
  ('cdp.identify', 'amplitude', '{byo}', 0.002),
  ('cdp.track', 'segment', '{byo}', 0.001),
  ('cdp.track', 'rudderstack', '{byo}', 0.001),
  ('cdp.track', 'mparticle', '{byo}', 0.002),
  ('cdp.track', 'mixpanel', '{byo}', 0.001),
  ('cdp.get_profile', 'segment', '{byo}', 0.004),
  ('cdp.get_profile', 'rudderstack', '{byo}', 0.003),
  ('cdp.get_profile', 'mparticle', '{byo}', 0.004),
  ('event_bus.publish', 'aws-eventbridge', '{byo}', 0.002),
  ('event_bus.publish', 'aws-sns', '{byo}', 0.001),
  ('event_bus.publish', 'google-pubsub', '{byo}', 0.002),
  ('event_bus.publish', 'confluent', '{byo}', 0.005),
  ('event_bus.publish', 'ably', '{byo}', 0.003),
  ('event_bus.subscribe', 'aws-eventbridge', '{byo}', 0.003),
  ('event_bus.subscribe', 'aws-sns', '{byo}', 0.001),
  ('event_bus.subscribe', 'google-pubsub', '{byo}', 0.002),
  ('event_bus.subscribe', 'ably', '{byo}', 0.003),
  ('event_bus.get_messages', 'aws-sqs', '{byo}', 0.001),
  ('event_bus.get_messages', 'google-pubsub', '{byo}', 0.002),
  ('event_bus.get_messages', 'confluent', '{byo}', 0.004),
  ('social_analytics.schedule_post', 'buffer', '{byo}', 0.003),
  ('social_analytics.schedule_post', 'hootsuite', '{byo}', 0.004),
  ('social_analytics.schedule_post', 'sprout-social', '{byo}', 0.006),
  ('social_analytics.schedule_post', 'later', '{byo}', 0.003),
  ('social_analytics.get_analytics', 'sprout-social', '{byo}', 0.006),
  ('social_analytics.get_analytics', 'hootsuite', '{byo}', 0.005),
  ('social_analytics.get_analytics', 'buffer', '{byo}', 0.004),
  ('contact.enrich', 'apollo', '{byo}', 0.005),
  ('contact.enrich', 'clearbit', '{byo}', 0.008),
  ('contact.enrich', 'pdl', '{byo}', 0.006),
  ('contact.enrich', 'hunter', '{byo}', 0.004),
  ('contact.search', 'apollo', '{byo}', 0.008),
  ('contact.search', 'pdl', '{byo}', 0.01),
  ('contact.search', 'clearbit', '{byo}', 0.01),
  ('contact.update', 'hubspot', '{byo}', 0.003),
  ('contact.update', 'salesforce', '{byo}', 0.004),
  ('contact.update', 'pipedrive', '{byo}', 0.003),
  ('booking_resource.search_availability', 'robin', '{byo}', 0.003),
  ('booking_resource.search_availability', 'skedda', '{byo}', 0.003),
  ('booking_resource.search_availability', 'microsoft-bookings', '{byo}', 0.002),
  ('booking_resource.search_availability', 'condeco', '{byo}', 0.004),
  ('booking_resource.reserve', 'robin', '{byo}', 0.004),
  ('booking_resource.reserve', 'skedda', '{byo}', 0.004),
  ('booking_resource.reserve', 'microsoft-bookings', '{byo}', 0.003),
  ('kyc.verify', 'persona', '{byo}', 0.02),
  ('kyc.verify', 'onfido', '{byo}', 0.025),
  ('kyc.verify', 'jumio', '{byo}', 0.03),
  ('kyc.verify', 'stripe-identity', '{byo}', 0.015),
  ('kyc.check_document', 'persona', '{byo}', 0.03),
  ('kyc.check_document', 'onfido', '{byo}', 0.035),
  ('kyc.check_document', 'jumio', '{byo}', 0.04),
  ('kyc.check_document', 'stripe-identity', '{byo}', 0.025),
  ('workflow.create', 'make', '{byo}', 0.01),
  ('workflow.create', 'zapier', '{byo}', 0.012),
  ('workflow.create', 'tray', '{byo}', 0.015),
  ('workflow.create', 'n8n', '{byo}', 0.005),
  ('workflow.trigger', 'make', '{byo}', 0.005),
  ('workflow.trigger', 'zapier', '{byo}', 0.006),
  ('workflow.trigger', 'tray', '{byo}', 0.008),
  ('workflow.trigger', 'n8n', '{byo}', 0.003),
  ('workflow.get_status', 'make', '{byo}', 0.003),
  ('workflow.get_status', 'zapier', '{byo}', 0.003),
  ('workflow.get_status', 'tray', '{byo}', 0.004),
  ('document_ai.extract_entities', 'google-documentai', '{byo}', 0.015),
  ('document_ai.extract_entities', 'aws-textract', '{byo}', 0.01),
  ('document_ai.extract_entities', 'azure-formrecognizer', '{byo}', 0.012),
  ('document_ai.extract_entities', 'reducto', '{byo}', 0.008),
  ('document_ai.classify', 'google-documentai', '{byo}', 0.01),
  ('document_ai.classify', 'aws-textract', '{byo}', 0.008),
  ('document_ai.classify', 'azure-formrecognizer', '{byo}', 0.009),
  ('asset.upload', 'cloudinary', '{byo}', 0.005),
  ('asset.upload', 'imgix', '{byo}', 0.004),
  ('asset.upload', 'uploadcare', '{byo}', 0.004),
  ('asset.upload', 'bunny', '{byo}', 0.003),
  ('asset.transform', 'cloudinary', '{byo}', 0.004),
  ('asset.transform', 'imgix', '{byo}', 0.003),
  ('asset.transform', 'uploadcare', '{byo}', 0.003),
  ('asset.get_url', 'cloudinary', '{byo}', 0.001),
  ('asset.get_url', 'imgix', '{byo}', 0.001),
  ('asset.get_url', 'bunny', '{byo}', 0.001),
  ('print.create_order', 'printful', '{byo}', 0.005),
  ('print.create_order', 'printify', '{byo}', 0.004),
  ('print.create_order', 'gooten', '{byo}', 0.005),
  ('print.create_order', 'gelato', '{byo}', 0.005),
  ('print.get_status', 'printful', '{byo}', 0.002),
  ('print.get_status', 'printify', '{byo}', 0.002),
  ('print.get_status', 'gelato', '{byo}', 0.002),
  ('iot.get_device_state', 'aws-iot', '{byo}', 0.003),
  ('iot.get_device_state', 'azure-iot-hub', '{byo}', 0.003),
  ('iot.get_device_state', 'google-iot', '{byo}', 0.003),
  ('iot.get_device_state', 'particle', '{byo}', 0.002),
  ('iot.send_command', 'aws-iot', '{byo}', 0.004),
  ('iot.send_command', 'azure-iot-hub', '{byo}', 0.004),
  ('iot.send_command', 'particle', '{byo}', 0.003),
  ('database.query', 'neon', '{byo}', 0.003),
  ('database.query', 'supabase', '{byo}', 0.003),
  ('database.query', 'planetscale', '{byo}', 0.004),
  ('database.query', 'turso', '{byo}', 0.002),
  ('database.execute', 'neon', '{byo}', 0.004),
  ('database.execute', 'supabase', '{byo}', 0.004),
  ('database.execute', 'planetscale', '{byo}', 0.005),
  ('database.execute', 'turso', '{byo}', 0.003),
  ('database.get_schema', 'neon', '{byo}', 0.002),
  ('database.get_schema', 'supabase', '{byo}', 0.002),
  ('database.get_schema', 'turso', '{byo}', 0.002),
  ('storage_object.put', 'aws-s3', '{byo}', 0.002),
  ('storage_object.put', 'cloudflare-r2', '{byo}', 0.001),
  ('storage_object.put', 'google-gcs', '{byo}', 0.002),
  ('storage_object.put', 'backblaze-b2', '{byo}', 0.001),
  ('storage_object.get', 'aws-s3', '{byo}', 0.001),
  ('storage_object.get', 'cloudflare-r2', '{byo}', 0.001),
  ('storage_object.get', 'google-gcs', '{byo}', 0.001),
  ('storage_object.delete', 'aws-s3', '{byo}', 0.001),
  ('storage_object.delete', 'cloudflare-r2', '{byo}', 0.001),
  ('storage_object.delete', 'google-gcs', '{byo}', 0.001),
  ('incident.create', 'pagerduty', '{byo}', 0.005),
  ('incident.create', 'opsgenie', '{byo}', 0.004),
  ('incident.create', 'grafana-oncall', '{byo}', 0.003),
  ('incident.create', 'victorops', '{byo}', 0.005),
  ('incident.update', 'pagerduty', '{byo}', 0.004),
  ('incident.update', 'opsgenie', '{byo}', 0.003),
  ('incident.update', 'grafana-oncall', '{byo}', 0.002),
  ('incident.resolve', 'pagerduty', '{byo}', 0.004),
  ('incident.resolve', 'opsgenie', '{byo}', 0.003),
  ('incident.resolve', 'grafana-oncall', '{byo}', 0.002),
  ('incident.resolve', 'victorops', '{byo}', 0.004),
  ('pos.charge', 'square', '{byo}', 0.005),
  ('pos.charge', 'stripe-terminal', '{byo}', 0.006),
  ('pos.charge', 'shopify-pos', '{byo}', 0.005),
  ('pos.get_transaction', 'square', '{byo}', 0.002),
  ('pos.get_transaction', 'stripe-terminal', '{byo}', 0.002),
  ('pos.get_transaction', 'shopify-pos', '{byo}', 0.002),
  ('pos.refund', 'square', '{byo}', 0.004),
  ('pos.refund', 'stripe-terminal', '{byo}', 0.004),
  ('pos.refund', 'shopify-pos', '{byo}', 0.003),
  ('gift_card.create', 'stripe', '{byo}', 0.005),
  ('gift_card.create', 'square', '{byo}', 0.004),
  ('gift_card.create', 'yift', '{byo}', 0.006),
  ('gift_card.get_balance', 'stripe', '{byo}', 0.002),
  ('gift_card.get_balance', 'square', '{byo}', 0.002),
  ('gift_card.get_balance', 'yift', '{byo}', 0.002),
  ('catalog.search_products', 'shopify', '{byo}', 0.002),
  ('catalog.search_products', 'salsify', '{byo}', 0.005),
  ('catalog.search_products', 'akeneo', '{byo}', 0.005),
  ('catalog.search_products', 'commercetools', '{byo}', 0.004),
  ('catalog.get_product', 'shopify', '{byo}', 0.002),
  ('catalog.get_product', 'salsify', '{byo}', 0.003),
  ('catalog.get_product', 'akeneo', '{byo}', 0.003),
  ('catalog.get_product', 'commercetools', '{byo}', 0.003),
  ('realtime.publish', 'pusher', '{byo}', 0.002),
  ('realtime.publish', 'ably', '{byo}', 0.002),
  ('realtime.publish', 'supabase-realtime', '{byo}', 0.001),
  ('realtime.publish', 'partykit', '{byo}', 0.002),
  ('realtime.subscribe', 'pusher', '{byo}', 0.003),
  ('realtime.subscribe', 'ably', '{byo}', 0.003),
  ('realtime.subscribe', 'supabase-realtime', '{byo}', 0.002),
  ('realtime.presence', 'pusher', '{byo}', 0.002),
  ('realtime.presence', 'ably', '{byo}', 0.002),
  ('realtime.presence', 'partykit', '{byo}', 0.002),
  ('travel.search_flights', 'amadeus', '{byo}', 0.01),
  ('travel.search_flights', 'skyscanner', '{byo}', 0.008),
  ('travel.search_flights', 'kiwi', '{byo}', 0.007),
  ('travel.search_flights', 'duffel', '{byo}', 0.01),
  ('travel.search_hotels', 'amadeus', '{byo}', 0.01),
  ('travel.search_hotels', 'booking-com', '{byo}', 0.008),
  ('travel.search_hotels', 'expedia', '{byo}', 0.009),
  ('travel.search_hotels', 'hotels-com', '{byo}', 0.008),
  ('payment_link.create', 'stripe', '{byo}', 0.004),
  ('payment_link.create', 'square', '{byo}', 0.003),
  ('payment_link.create', 'paypal', '{byo}', 0.004),
  ('payment_link.create', 'paddle', '{byo}', 0.004),
  ('payment_link.get', 'stripe', '{byo}', 0.002),
  ('payment_link.get', 'square', '{byo}', 0.002),
  ('payment_link.get', 'paypal', '{byo}', 0.002),
  ('resume.parse', 'affinda', '{byo}', 0.01),
  ('resume.parse', 'sovren', '{byo}', 0.015),
  ('resume.parse', 'hireability', '{byo}', 0.012),
  ('resume.match', 'affinda', '{byo}', 0.015),
  ('resume.match', 'sovren', '{byo}', 0.02),
  ('resume.match', 'skillate', '{byo}', 0.018),
  ('resume.score', 'affinda', '{byo}', 0.012),
  ('resume.score', 'jobscan', '{byo}', 0.01),
  ('resume.score', 'skillate', '{byo}', 0.015),
  ('fraud.score_transaction', 'signifyd', '{byo}', 0.01),
  ('fraud.score_transaction', 'stripe-radar', '{byo}', 0.005),
  ('fraud.score_transaction', 'kount', '{byo}', 0.012),
  ('fraud.score_transaction', 'sift', '{byo}', 0.008),
  ('fraud.flag_user', 'sift', '{byo}', 0.006),
  ('fraud.flag_user', 'signifyd', '{byo}', 0.008),
  ('fraud.flag_user', 'kount', '{byo}', 0.009),
  ('fraud.review', 'signifyd', '{byo}', 0.005),
  ('fraud.review', 'sift', '{byo}', 0.004),
  ('fraud.review', 'kount', '{byo}', 0.006),
  ('video_conference.create_meeting', 'zoom', '{byo}', 0.005),
  ('video_conference.create_meeting', 'daily', '{byo}', 0.004),
  ('video_conference.create_meeting', 'google-meet', '{byo}', 0.003),
  ('video_conference.create_meeting', 'whereby', '{byo}', 0.004),
  ('video_conference.get_recording', 'zoom', '{byo}', 0.003),
  ('video_conference.get_recording', 'daily', '{byo}', 0.003),
  ('video_conference.get_recording', 'google-meet', '{byo}', 0.002),
  ('review.request', 'yotpo', '{byo}', 0.004),
  ('review.request', 'trustpilot', '{byo}', 0.005),
  ('review.request', 'bazaarvoice', '{byo}', 0.006),
  ('review.request', 'okendo', '{byo}', 0.004),
  ('review.get_summary', 'yotpo', '{byo}', 0.003),
  ('review.get_summary', 'trustpilot', '{byo}', 0.004),
  ('review.get_summary', 'bazaarvoice', '{byo}', 0.004),
  ('legal.search_entity', 'opencorporates', '{byo}', 0.005),
  ('legal.search_entity', 'dnb', '{byo}', 0.01),
  ('legal.search_entity', 'gleif', '{byo}', 0.003),
  ('legal.check_sanctions', 'complyadvantage', '{byo}', 0.015),
  ('legal.check_sanctions', 'refinitiv', '{byo}', 0.02),
  ('legal.check_sanctions', 'dowjones-riskscreening', '{byo}', 0.018),
  ('legal.get_filings', 'opencorporates', '{byo}', 0.006),
  ('legal.get_filings', 'sec-edgar', '{byo}', 0.002),
  ('legal.get_filings', 'dnb', '{byo}', 0.008),
  ('lead.create', 'hubspot', '{byo}', 0.003),
  ('lead.create', 'salesforce', '{byo}', 0.004),
  ('lead.create', 'marketo', '{byo}', 0.005),
  ('lead.create', 'pardot', '{byo}', 0.004),
  ('lead.score', 'madkudu', '{byo}', 0.01),
  ('lead.score', 'hubspot', '{byo}', 0.004),
  ('lead.score', 'clearbit', '{byo}', 0.008),
  ('lead.assign', 'hubspot', '{byo}', 0.003),
  ('lead.assign', 'salesforce', '{byo}', 0.003),
  ('lead.assign', 'pipedrive', '{byo}', 0.003),
  ('quote.create', 'pandadoc', '{byo}', 0.01),
  ('quote.create', 'hubspot-quotes', '{byo}', 0.006),
  ('quote.create', 'proposify', '{byo}', 0.009),
  ('quote.create', 'better-proposals', '{byo}', 0.007),
  ('quote.send', 'pandadoc', '{byo}', 0.005),
  ('quote.send', 'hubspot-quotes', '{byo}', 0.004),
  ('quote.send', 'proposify', '{byo}', 0.005),
  ('quote.get_status', 'pandadoc', '{byo}', 0.003),
  ('quote.get_status', 'hubspot-quotes', '{byo}', 0.002),
  ('quote.get_status', 'proposify', '{byo}', 0.003),
  ('waitlist.join', 'waitlistapi', '{byo}', 0.002),
  ('waitlist.join', 'getwaitlist', '{byo}', 0.002),
  ('waitlist.join', 'prefinery', '{byo}', 0.003),
  ('waitlist.get_position', 'waitlistapi', '{byo}', 0.001),
  ('waitlist.get_position', 'getwaitlist', '{byo}', 0.001),
  ('waitlist.get_position', 'prefinery', '{byo}', 0.002),
  ('social_listening.search_mentions', 'brandwatch', '{byo}', 0.015),
  ('social_listening.search_mentions', 'mention', '{byo}', 0.008),
  ('social_listening.search_mentions', 'sprinklr', '{byo}', 0.02),
  ('social_listening.search_mentions', 'talkwalker', '{byo}', 0.018),
  ('social_listening.get_alerts', 'brandwatch', '{byo}', 0.005),
  ('social_listening.get_alerts', 'mention', '{byo}', 0.004),
  ('social_listening.get_alerts', 'talkwalker', '{byo}', 0.006),
  ('affiliate.create_link', 'impact', '{byo}', 0.004),
  ('affiliate.create_link', 'partnerstack', '{byo}', 0.004),
  ('affiliate.create_link', 'rewardful', '{byo}', 0.003),
  ('affiliate.create_link', 'shareasale', '{byo}', 0.004),
  ('affiliate.get_stats', 'impact', '{byo}', 0.005),
  ('affiliate.get_stats', 'partnerstack', '{byo}', 0.005),
  ('affiliate.get_stats', 'rewardful', '{byo}', 0.003),
  ('affiliate.get_commissions', 'impact', '{byo}', 0.004),
  ('affiliate.get_commissions', 'partnerstack', '{byo}', 0.004),
  ('affiliate.get_commissions', 'rewardful', '{byo}', 0.003),
  ('news.search', 'newsapi', '{byo}', 0.004),
  ('news.search', 'bing-news', '{byo}', 0.005),
  ('news.search', 'guardian', '{byo}', 0.002),
  ('news.search', 'nyt', '{byo}', 0.003),
  ('news.get_headlines', 'newsapi', '{byo}', 0.003),
  ('news.get_headlines', 'bing-news', '{byo}', 0.004),
  ('news.get_headlines', 'guardian', '{byo}', 0.002),
  ('data_warehouse.query', 'bigquery', '{byo}', 0.01),
  ('data_warehouse.query', 'snowflake', '{byo}', 0.012),
  ('data_warehouse.query', 'redshift', '{byo}', 0.01),
  ('data_warehouse.query', 'databricks', '{byo}', 0.015),
  ('data_warehouse.run_job', 'bigquery', '{byo}', 0.015),
  ('data_warehouse.run_job', 'snowflake', '{byo}', 0.018),
  ('data_warehouse.run_job', 'databricks', '{byo}', 0.02),
  ('certificate.issue', 'digicert', '{byo}', 0.02),
  ('certificate.issue', 'aws-acm', '{byo}', 0.005),
  ('certificate.issue', 'sectigo', '{byo}', 0.015),
  ('certificate.issue', 'zerossl', '{byo}', 0.005),
  ('certificate.get_status', 'digicert', '{byo}', 0.005),
  ('certificate.get_status', 'aws-acm', '{byo}', 0.002),
  ('certificate.get_status', 'sectigo', '{byo}', 0.004),
  ('certificate.revoke', 'digicert', '{byo}', 0.01),
  ('certificate.revoke', 'aws-acm', '{byo}', 0.004),
  ('certificate.revoke', 'zerossl', '{byo}', 0.003),
  ('accessibility.scan', 'deque-axe', '{byo}', 0.005),
  ('accessibility.scan', 'wave', '{byo}', 0.004),
  ('accessibility.scan', 'pa11y', '{byo}', 0.003),
  ('accessibility.scan', 'siteimprove', '{byo}', 0.008),
  ('accessibility.report', 'deque-axe', '{byo}', 0.01),
  ('accessibility.report', 'siteimprove', '{byo}', 0.015),
  ('accessibility.report', 'wave', '{byo}', 0.008),
  ('load_test.run', 'k6-cloud', '{byo}', 0.02),
  ('load_test.run', 'artillery-cloud', '{byo}', 0.015),
  ('load_test.run', 'gatling-cloud', '{byo}', 0.018),
  ('load_test.get_results', 'k6-cloud', '{byo}', 0.005),
  ('load_test.get_results', 'artillery-cloud', '{byo}', 0.004),
  ('load_test.get_results', 'gatling-cloud', '{byo}', 0.004),
  ('load_test.get_metrics', 'k6-cloud', '{byo}', 0.008),
  ('load_test.get_metrics', 'gatling-cloud', '{byo}', 0.006),
  ('sports.get_scores', 'sportradar', '{byo}', 0.01),
  ('sports.get_scores', 'thesportsdb', '{byo}', 0.003),
  ('sports.get_scores', 'api-sports', '{byo}', 0.005),
  ('sports.get_schedule', 'sportradar', '{byo}', 0.008),
  ('sports.get_schedule', 'thesportsdb', '{byo}', 0.002),
  ('sports.get_schedule', 'api-sports', '{byo}', 0.004),
  ('sports.get_standings', 'sportradar', '{byo}', 0.008),
  ('sports.get_standings', 'thesportsdb', '{byo}', 0.002),
  ('sports.get_standings', 'api-sports', '{byo}', 0.004),
  ('backup.create', 'aws-backup', '{byo}', 0.005),
  ('backup.create', 'azure-backup', '{byo}', 0.005),
  ('backup.create', 'backblaze-b2', '{byo}', 0.003),
  ('backup.create', 'veeam', '{byo}', 0.008),
  ('backup.get_status', 'aws-backup', '{byo}', 0.002),
  ('backup.get_status', 'azure-backup', '{byo}', 0.002),
  ('backup.get_status', 'veeam', '{byo}', 0.003),
  ('image_moderation.check_image', 'aws-rekognition', '{byo}', 0.005),
  ('image_moderation.check_image', 'azure-content-moderator', '{byo}', 0.005),
  ('image_moderation.check_image', 'hive', '{byo}', 0.006),
  ('image_moderation.check_image', 'sightengine', '{byo}', 0.004),
  ('image_moderation.check_text', 'openai-moderation', '{byo}', 0.001),
  ('image_moderation.check_text', 'azure-content-moderator', '{byo}', 0.003),
  ('image_moderation.check_text', 'hive', '{byo}', 0.004),
  ('image_moderation.check_text', 'perspective', '{byo}', 0.002),
  ('image_moderation.get_report', 'aws-rekognition', '{byo}', 0.002),
  ('image_moderation.get_report', 'hive', '{byo}', 0.002),
  ('domain_registration.search_availability', 'namecheap', '{byo}', 0.003),
  ('domain_registration.search_availability', 'godaddy', '{byo}', 0.003),
  ('domain_registration.search_availability', 'cloudflare-registrar', '{byo}', 0.002),
  ('domain_registration.search_availability', 'porkbun', '{byo}', 0.002),
  ('domain_registration.register', 'namecheap', '{byo}', 0.01),
  ('domain_registration.register', 'godaddy', '{byo}', 0.012),
  ('domain_registration.register', 'cloudflare-registrar', '{byo}', 0.008),
  ('domain_registration.get_info', 'namecheap', '{byo}', 0.002),
  ('domain_registration.get_info', 'godaddy', '{byo}', 0.002),
  ('domain_registration.get_info', 'whoisjson', '{byo}', 0.001),
  ('address_verification.verify', 'smarty', '{byo}', 0.005),
  ('address_verification.verify', 'lob', '{byo}', 0.006),
  ('address_verification.verify', 'google-address', '{byo}', 0.004),
  ('address_verification.verify', 'melissa', '{byo}', 0.005),
  ('address_verification.autocomplete', 'google-places', '{byo}', 0.003),
  ('address_verification.autocomplete', 'smarty', '{byo}', 0.004),
  ('address_verification.autocomplete', 'here', '{byo}', 0.003),
  ('fleet.track_vehicle', 'samsara', '{byo}', 0.005),
  ('fleet.track_vehicle', 'geotab', '{byo}', 0.005),
  ('fleet.track_vehicle', 'verizon-connect', '{byo}', 0.006),
  ('fleet.get_location_history', 'samsara', '{byo}', 0.006),
  ('fleet.get_location_history', 'geotab', '{byo}', 0.006),
  ('fleet.get_location_history', 'verizon-connect', '{byo}', 0.007),
  ('conversation_intelligence.analyze_call', 'gong', '{byo}', 0.02),
  ('conversation_intelligence.analyze_call', 'chorus', '{byo}', 0.018),
  ('conversation_intelligence.analyze_call', 'fireflies', '{byo}', 0.01),
  ('conversation_intelligence.analyze_call', 'clari', '{byo}', 0.022),
  ('conversation_intelligence.get_transcript', 'gong', '{byo}', 0.008),
  ('conversation_intelligence.get_transcript', 'chorus', '{byo}', 0.007),
  ('conversation_intelligence.get_transcript', 'fireflies', '{byo}', 0.005),
  ('conversation_intelligence.get_insights', 'gong', '{byo}', 0.01),
  ('conversation_intelligence.get_insights', 'chorus', '{byo}', 0.009),
  ('conversation_intelligence.get_insights', 'clari', '{byo}', 0.012),
  ('geofence.create', 'radar', '{byo}', 0.004),
  ('geofence.create', 'here', '{byo}', 0.005),
  ('geofence.create', 'google-maps', '{byo}', 0.005),
  ('geofence.check', 'radar', '{byo}', 0.002),
  ('geofence.check', 'here', '{byo}', 0.003),
  ('geofence.check', 'google-maps', '{byo}', 0.003),
  ('geofence.list_events', 'radar', '{byo}', 0.003),
  ('geofence.list_events', 'here', '{byo}', 0.004),
  ('package.search', 'npm-registry', '{byo}', 0.001),
  ('package.search', 'pypi', '{byo}', 0.001),
  ('package.search', 'crates-io', '{byo}', 0.001),
  ('package.search', 'libraries-io', '{byo}', 0.003),
  ('package.get_info', 'npm-registry', '{byo}', 0.001),
  ('package.get_info', 'pypi', '{byo}', 0.001),
  ('package.get_info', 'libraries-io', '{byo}', 0.002),
  ('forecast.run', 'aws-forecast', '{byo}', 0.02),
  ('forecast.run', 'nixtla', '{byo}', 0.01),
  ('forecast.run', 'google-vertex-forecast', '{byo}', 0.018),
  ('forecast.get_results', 'aws-forecast', '{byo}', 0.005),
  ('forecast.get_results', 'nixtla', '{byo}', 0.004),
  ('forecast.get_results', 'google-vertex-forecast', '{byo}', 0.005)
ON CONFLICT (capability_id, service_slug) DO UPDATE SET
  credential_modes = EXCLUDED.credential_modes,
  cost_per_call = EXCLUDED.cost_per_call,
  updated_at = now();

COMMIT;
