-- Migration 0166: Seed hosted Index command manifest storage
--
-- Deterministic PP-2 fixture seed for index_command_manifests. These rows
-- preserve manifest/evidence digests and public claim boundaries exactly;
-- they do not claim live production execution. Evidence columns are filled
-- only where an Index evidence packet fixture already exists.

BEGIN;

INSERT INTO index_command_manifests (
    route_id,
    manifest_id,
    manifest_version,
    manifest_digest,
    service_id,
    provider_id,
    capability_id,
    substrate,
    provenance_origin,
    source_risk,
    side_effect_class,
    promotion_state,
    review_status,
    evidence_packet_id,
    evidence_packet_digest,
    evidence_expires_at,
    public_claim_boundary,
    manifest_json,
    evidence_packet_json,
    owner,
    reviewer,
    expires_at
)
VALUES
    (
        'route_calendar_freebusy_generated_adapter_v1',
        'manifest_generated_calendar_freebusy_fixture_v1',
        '2026-05-19.1',
        'sha256:bc8b9916a1122e58d66baf8ddd50c3b6ee0b4734a467211f77868f004657fbb5',
        'google-calendar',
        'generated-calendar-adapter',
        'calendar.freebusy',
        'generated_adapter',
        'rhumb_generated',
        'community_unverified',
        'read',
        'fixture_only',
        NULL,
        NULL,
        NULL,
        NULL,
        'Fixture-only generated adapter candidate; Rhumb must not describe it as approved by the vendor or production ready before evidence, sandbox, and review gates pass.',
        '{"artifact_allowlist":["generated-calendar-adapter@fixture-digest-placeholder"],"auth_mode":"agent_vault","cache_behavior":"none","capability_id":"calendar.freebusy","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["calendar_availability"],"dry_run_supported":false,"evidence_refs":["evidence:route_calendar_freebusy_generated_adapter_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:bc8b9916a1122e58d66baf8ddd50c3b6ee0b4734a467211f77868f004657fbb5","manifest_id":"manifest_generated_calendar_freebusy_fixture_v1","manifest_version":"2026-05-19.1","network_allowlist":["www.googleapis.com"],"owner":"Pedro","process_allowlist":["python"],"promotion_state":"fixture_only","provenance_origin":"rhumb_generated","provider_id":"generated-calendar-adapter","public_claim_boundary":"Fixture-only generated adapter candidate; Rhumb must not describe it as approved by the vendor or production ready before evidence, sandbox, and review gates pass.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":[],"required_scopes":[],"reviewer":"Pedro","route_id":"route_calendar_freebusy_generated_adapter_v1","route_name":"calendar.freebusy via generated adapter fixture","sandbox_profile_class":"generated_adapter_readonly_fixture","service_id":"google-calendar","side_effect_class":"read","source_risk":"community_unverified","substrate":"generated_adapter","tests":["test_manifest_route_calendar_freebusy_generated_adapter_v1"],"vendor":"Google Calendar"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_crm_contact_lookup_salesforce_api_official_api_v1',
        'manifest_crm_contact_lookup_salesforce_api_official_api_v1',
        '2026-05-19.1',
        'sha256:b36192fc5873116ede939d10cfd6ad0a5b9daf2512515371f5f791c555b4e031',
        'salesforce',
        'salesforce-api',
        'crm.contact.lookup',
        'official_api',
        'rhumb_managed',
        'verified_low',
        'read',
        'beta_executable',
        NULL,
        NULL,
        NULL,
        NULL,
        'Rhumb can represent the crm.contact.lookup managed official API route when governed auth, budget, and policy allow it.',
        '{"artifact_allowlist":[],"auth_mode":"rhumb_managed","cache_behavior":"none","capability_id":"crm.contact.lookup","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["crm_contact"],"dry_run_supported":false,"evidence_refs":["evidence:route_crm_contact_lookup_salesforce_api_official_api_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:b36192fc5873116ede939d10cfd6ad0a5b9daf2512515371f5f791c555b4e031","manifest_id":"manifest_crm_contact_lookup_salesforce_api_official_api_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.salesforce.example.com"],"owner":"Pedro","process_allowlist":[],"promotion_state":"beta_executable","provenance_origin":"rhumb_managed","provider_id":"salesforce-api","public_claim_boundary":"Rhumb can represent the crm.contact.lookup managed official API route when governed auth, budget, and policy allow it.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":["salesforce-api:api_key"],"required_scopes":[],"reviewer":"Pedro","route_id":"route_crm_contact_lookup_salesforce_api_official_api_v1","route_name":"crm.contact.lookup via salesforce-api official API","service_id":"salesforce","side_effect_class":"read","source_risk":"verified_low","substrate":"official_api","tests":["test_manifest_route_crm_contact_lookup_salesforce_api_official_api_v1"],"vendor":"salesforce"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_customer_retrieve_stripe_sdk_code_mode_v1',
        'manifest_stripe_customer_retrieve_sdk_code_v1',
        '2026-05-19.1',
        'sha256:af34bda7f48ec62fe7c070dd1045829ddd3d6320578593a7c9438f22b6f9f8b8',
        'stripe',
        'stripe-sdk',
        'customer.retrieve',
        'sdk_code_mode',
        'vendor_official',
        'community_unverified',
        'read',
        'fixture_only',
        NULL,
        NULL,
        NULL,
        NULL,
        'Fixture-only route describing a pinned official Stripe SDK read path after code-mode sandbox gates pass.',
        '{"artifact_allowlist":["stripe-python@pinned-digest-placeholder"],"auth_mode":"agent_vault","cache_behavior":"none","capability_id":"customer.retrieve","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["customer_profile"],"dry_run_supported":false,"evidence_refs":["evidence:route_customer_retrieve_stripe_sdk_code_mode_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:af34bda7f48ec62fe7c070dd1045829ddd3d6320578593a7c9438f22b6f9f8b8","manifest_id":"manifest_stripe_customer_retrieve_sdk_code_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.stripe.com"],"owner":"Pedro","process_allowlist":["python"],"promotion_state":"fixture_only","provenance_origin":"vendor_official","provider_id":"stripe-sdk","public_claim_boundary":"Fixture-only route describing a pinned official Stripe SDK read path after code-mode sandbox gates pass.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":[],"required_scopes":[],"reviewer":"Pedro","route_id":"route_customer_retrieve_stripe_sdk_code_mode_v1","route_name":"customer.retrieve via official SDK code-mode fixture","sandbox_profile_class":"sdk_code_readonly_network_stripe","service_id":"stripe","side_effect_class":"read","source_risk":"community_unverified","substrate":"sdk_code_mode","tests":["test_manifest_route_customer_retrieve_stripe_sdk_code_mode_v1"],"vendor":"Stripe"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_email_verify_emailable_api_official_api_v1',
        'manifest_email_verify_emailable_api_official_api_v1',
        '2026-05-19.1',
        'sha256:51b416b5febdf2ebfa50df20959e5f055f9ff058e546151445bcef45023d15eb',
        'emailable',
        'emailable-api',
        'email.verify',
        'official_api',
        'rhumb_managed',
        'verified_low',
        'read',
        'beta_executable',
        NULL,
        NULL,
        NULL,
        NULL,
        'Rhumb can represent the email.verify managed official API route when governed auth, budget, and policy allow it.',
        '{"artifact_allowlist":[],"auth_mode":"rhumb_managed","cache_behavior":"none","capability_id":"email.verify","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["email_address"],"dry_run_supported":false,"evidence_refs":["evidence:route_email_verify_emailable_api_official_api_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:51b416b5febdf2ebfa50df20959e5f055f9ff058e546151445bcef45023d15eb","manifest_id":"manifest_email_verify_emailable_api_official_api_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.emailable.example.com"],"owner":"Pedro","process_allowlist":[],"promotion_state":"beta_executable","provenance_origin":"rhumb_managed","provider_id":"emailable-api","public_claim_boundary":"Rhumb can represent the email.verify managed official API route when governed auth, budget, and policy allow it.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":["emailable-api:api_key"],"required_scopes":[],"reviewer":"Pedro","route_id":"route_email_verify_emailable_api_official_api_v1","route_name":"email.verify via emailable-api official API","service_id":"emailable","side_effect_class":"read","source_risk":"verified_low","substrate":"official_api","tests":["test_manifest_route_email_verify_emailable_api_official_api_v1"],"vendor":"emailable"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_file_search_official_mcp_v1',
        'manifest_filesystem_search_official_mcp_v1',
        '2026-05-19.1',
        'sha256:01f0bedd335144423455a1a0cd94c59937db9153e5d2956c6e5f2798b4dfa5fc',
        'filesystem',
        'filesystem-mcp',
        'file.search',
        'official_mcp',
        'vendor_official',
        'community_unverified',
        'read',
        'fixture_only',
        NULL,
        NULL,
        NULL,
        NULL,
        'Fixture-only route describing a pinned read-only MCP filesystem search path after sandbox and consent gates pass.',
        '{"artifact_allowlist":["mcp-filesystem@pinned-digest-placeholder"],"auth_mode":"none","cache_behavior":"none","capability_id":"file.search","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["local_file_metadata"],"dry_run_supported":false,"evidence_refs":["evidence:route_file_search_official_mcp_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":["/tmp/rhumb-fixtures/read-only"],"manifest_digest":"sha256:01f0bedd335144423455a1a0cd94c59937db9153e5d2956c6e5f2798b4dfa5fc","manifest_id":"manifest_filesystem_search_official_mcp_v1","manifest_version":"2026-05-19.1","network_allowlist":["none"],"owner":"Pedro","process_allowlist":["node"],"promotion_state":"fixture_only","provenance_origin":"vendor_official","provider_id":"filesystem-mcp","public_claim_boundary":"Fixture-only route describing a pinned read-only MCP filesystem search path after sandbox and consent gates pass.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":[],"required_scopes":[],"reviewer":"Pedro","route_id":"route_file_search_official_mcp_v1","route_name":"file.search via official MCP server fixture","sandbox_profile_class":"mcp_readonly_filesystem_fixture","service_id":"filesystem","side_effect_class":"read","source_risk":"community_unverified","substrate":"official_mcp","tests":["test_manifest_route_file_search_official_mcp_v1"],"vendor":"Model Context Protocol"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_search_query_brave_search_api_official_api_v1',
        'manifest_search_query_brave_search_api_official_api_v1',
        '2026-05-19.1',
        'sha256:500330f51d0cc678ab9eb1427858d116df15c4c047c1aadb39c465ac343dade2',
        'brave-search',
        'brave-search-api',
        'search.query',
        'official_api',
        'rhumb_managed',
        'verified_low',
        'read',
        'beta_executable',
        'current',
        'evidence_search_query_brave_search_api_official_api_2026_05_19',
        'sha256:d8976c9766905eaa2c08987205f056ce24520665874bb2dab48461a3e7561c2a',
        '2026-08-17T00:00:00Z'::timestamptz,
        'Rhumb can represent the search.query managed official API route when governed auth, budget, and policy allow it.',
        '{"artifact_allowlist":[],"auth_mode":"rhumb_managed","cache_behavior":"none","capability_id":"search.query","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["web_search_query"],"dry_run_supported":false,"evidence_refs":["evidence:route_search_query_brave_search_api_official_api_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:500330f51d0cc678ab9eb1427858d116df15c4c047c1aadb39c465ac343dade2","manifest_id":"manifest_search_query_brave_search_api_official_api_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.brave-search.example.com"],"owner":"Pedro","process_allowlist":[],"promotion_state":"beta_executable","provenance_origin":"rhumb_managed","provider_id":"brave-search-api","public_claim_boundary":"Rhumb can represent the search.query managed official API route when governed auth, budget, and policy allow it.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":["brave-search-api:api_key"],"required_scopes":[],"reviewer":"Pedro","route_id":"route_search_query_brave_search_api_official_api_v1","route_name":"search.query via brave-search-api official API","service_id":"brave-search","side_effect_class":"read","source_risk":"verified_low","substrate":"official_api","tests":["test_manifest_route_search_query_brave_search_api_official_api_v1"],"vendor":"brave-search"}'::jsonb,
        '{"an_score_input_refs":["scores:service:brave-search"],"capability_id":"search.query","credential_modes":["rhumb_managed"],"evidence_expires_at":"2026-08-17T00:00:00Z","evidence_packet_digest":"sha256:d8976c9766905eaa2c08987205f056ce24520665874bb2dab48461a3e7561c2a","evidence_packet_id":"evidence_search_query_brave_search_api_official_api_2026_05_19","freshness_checked_at":"2026-05-19T17:05:18Z","manifest_digest":"sha256:e84b79fa73722472c846e4b7f352b9d444adae73edb91150a51aee8329d3524a","manifest_id":"manifest_search_query_brave_search_api_official_api_v1","manifest_version":"2026-05-19.1","owner":"Pedro","promotion_state":"beta_executable","provenance_origin":"rhumb_managed","provider_id":"brave-search-api","public_claim_boundary":"Rhumb can route read-only web search queries through a Rhumb-managed Brave Search API route when the caller has a valid governed Rhumb key and available credit.","resolve_separation_note":"This packet supports route trust. Resolve still decides per-user auth, budget, policy, and risk at request time.","review_status":"current","reviewer":"Pedro","reviews":[{"reviewed_at":"2026-05-19T17:05:18Z","reviewer":"Pedro","scope":"schema_and_source_fixture; live first-call receipt lands in PP-9","verdict":"current_for_core_fixture"}],"route_id":"route_search_query_brave_search_api_official_api_v1","runtime_witnesses":[{"capability_id":"search.query","kind":"planned_first_call_fixture","provider_id":"brave-search-api","status":"pending_PP-9_live_receipt"}],"service_id":"brave-search","side_effect_class":"read","source_risk":"verified_low","sources":[{"kind":"vendor_docs","observed_at":"2026-05-19T17:05:18Z","observed_title":"Documentation - Brave Search API","url":"https://api-dashboard.search.brave.com/app/documentation/web-search/get-started"},{"kind":"rhumb_contract","observed_at":"2026-05-19T17:05:18Z","url":"docs/INDEX-RESOLVE-VNEXT-PRD-ROADMAP-2026-05-19.md#core-searchquery-index-fixture"}],"substrate":"official_api"}'::jsonb,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_support_ticket_create_zendesk_api_official_api_v1',
        'manifest_support_ticket_create_zendesk_api_official_api_v1',
        '2026-05-19.1',
        'sha256:e274aa5195cf74e98cf66eed3e683b80a3670045a17fe5503d3a68bed2cae7ce',
        'zendesk',
        'zendesk-api',
        'support.ticket.create',
        'official_api',
        'rhumb_managed',
        'verified_low',
        'write',
        'beta_executable',
        NULL,
        NULL,
        NULL,
        NULL,
        'Rhumb can represent the support.ticket.create managed official API route when governed auth, budget, and policy allow it.',
        '{"artifact_allowlist":[],"auth_mode":"rhumb_managed","cache_behavior":"none","capability_id":"support.ticket.create","confirmation_policy":"dry_run_then_confirm","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["support_ticket"],"dry_run_supported":true,"evidence_refs":["evidence:route_support_ticket_create_zendesk_api_official_api_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:e274aa5195cf74e98cf66eed3e683b80a3670045a17fe5503d3a68bed2cae7ce","manifest_id":"manifest_support_ticket_create_zendesk_api_official_api_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.zendesk.example.com"],"owner":"Pedro","process_allowlist":[],"promotion_state":"beta_executable","provenance_origin":"rhumb_managed","provider_id":"zendesk-api","public_claim_boundary":"Rhumb can represent the support.ticket.create managed official API route when governed auth, budget, and policy allow it.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":["zendesk-api:api_key"],"required_scopes":[],"reviewer":"Pedro","route_id":"route_support_ticket_create_zendesk_api_official_api_v1","route_name":"support.ticket.create via zendesk-api official API","service_id":"zendesk","side_effect_class":"write","source_risk":"verified_low","substrate":"official_api","tests":["test_manifest_route_support_ticket_create_zendesk_api_official_api_v1"],"vendor":"zendesk"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_warehouse_query_snowflake_api_official_api_v1',
        'manifest_warehouse_query_snowflake_api_official_api_v1',
        '2026-05-19.1',
        'sha256:bf89210fbb4d4286de046a17715fa98e2ac1643e552947e99dedd265ae393220',
        'snowflake',
        'snowflake-api',
        'warehouse.query',
        'official_api',
        'rhumb_managed',
        'verified_low',
        'read',
        'beta_executable',
        NULL,
        NULL,
        NULL,
        NULL,
        'Rhumb can represent the warehouse.query managed official API route when governed auth, budget, and policy allow it.',
        '{"artifact_allowlist":[],"auth_mode":"rhumb_managed","cache_behavior":"none","capability_id":"warehouse.query","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["warehouse_query"],"dry_run_supported":false,"evidence_refs":["evidence:route_warehouse_query_snowflake_api_official_api_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:bf89210fbb4d4286de046a17715fa98e2ac1643e552947e99dedd265ae393220","manifest_id":"manifest_warehouse_query_snowflake_api_official_api_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.snowflake.example.com"],"owner":"Pedro","process_allowlist":[],"promotion_state":"beta_executable","provenance_origin":"rhumb_managed","provider_id":"snowflake-api","public_claim_boundary":"Rhumb can represent the warehouse.query managed official API route when governed auth, budget, and policy allow it.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":["snowflake-api:api_key"],"required_scopes":[],"reviewer":"Pedro","route_id":"route_warehouse_query_snowflake_api_official_api_v1","route_name":"warehouse.query via snowflake-api official API","service_id":"snowflake","side_effect_class":"read","source_risk":"verified_low","substrate":"official_api","tests":["test_manifest_route_warehouse_query_snowflake_api_official_api_v1"],"vendor":"snowflake"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    ),
    (
        'route_workflow_run_list_github_cli_v1',
        'manifest_github_workflow_list_official_cli_v1',
        '2026-05-19.1',
        'sha256:4bd0fa611792130576998c6c7bb3de695d6554a212bb2f151798d60713b20b76',
        'github',
        'github-cli',
        'workflow_run.list',
        'official_cli',
        'vendor_official',
        'community_unverified',
        'read',
        'fixture_only',
        NULL,
        NULL,
        NULL,
        NULL,
        'Fixture-only route describing how a pinned official GitHub CLI could list workflow runs after non-native sandbox gates pass.',
        '{"artifact_allowlist":["gh@pinned-digest-placeholder"],"auth_mode":"agent_vault","cache_behavior":"none","capability_id":"workflow_run.list","confirmation_policy":"none","cost_model":{"estimated_cost_usd":0.003,"unit":"call"},"data_classes":["workflow_metadata"],"dry_run_supported":false,"evidence_refs":["evidence:route_workflow_run_list_github_cli_v1"],"expires_at":"2026-08-17T00:00:00Z","filesystem_allowlist":[],"manifest_digest":"sha256:4bd0fa611792130576998c6c7bb3de695d6554a212bb2f151798d60713b20b76","manifest_id":"manifest_github_workflow_list_official_cli_v1","manifest_version":"2026-05-19.1","network_allowlist":["api.github.com"],"owner":"Pedro","process_allowlist":["gh"],"promotion_state":"fixture_only","provenance_origin":"vendor_official","provider_id":"github-cli","public_claim_boundary":"Fixture-only route describing how a pinned official GitHub CLI could list workflow runs after non-native sandbox gates pass.","rate_limit_model":{"enforced_by":"rhumb","limit":60,"unit":"minute"},"required_credentials":[],"required_scopes":[],"reviewer":"Pedro","route_id":"route_workflow_run_list_github_cli_v1","route_name":"workflow_run.list via official GitHub CLI","sandbox_profile_class":"cli_readonly_network_github","service_id":"github","side_effect_class":"read","source_risk":"community_unverified","substrate":"official_cli","tests":["test_manifest_route_workflow_run_list_github_cli_v1"],"vendor":"GitHub"}'::jsonb,
        NULL,
        'Pedro',
        'Pedro',
        '2026-08-17T00:00:00Z'::timestamptz
    )
ON CONFLICT (route_id) DO UPDATE SET
    manifest_id = EXCLUDED.manifest_id,
    manifest_version = EXCLUDED.manifest_version,
    manifest_digest = EXCLUDED.manifest_digest,
    service_id = EXCLUDED.service_id,
    provider_id = EXCLUDED.provider_id,
    capability_id = EXCLUDED.capability_id,
    substrate = EXCLUDED.substrate,
    provenance_origin = EXCLUDED.provenance_origin,
    source_risk = EXCLUDED.source_risk,
    side_effect_class = EXCLUDED.side_effect_class,
    promotion_state = EXCLUDED.promotion_state,
    review_status = EXCLUDED.review_status,
    evidence_packet_id = EXCLUDED.evidence_packet_id,
    evidence_packet_digest = EXCLUDED.evidence_packet_digest,
    evidence_expires_at = EXCLUDED.evidence_expires_at,
    public_claim_boundary = EXCLUDED.public_claim_boundary,
    manifest_json = EXCLUDED.manifest_json,
    evidence_packet_json = EXCLUDED.evidence_packet_json,
    owner = EXCLUDED.owner,
    reviewer = EXCLUDED.reviewer,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW();

COMMIT;
