"""Hand-scored fixtures used for AN score calibration tests."""

from __future__ import annotations

from typing import Any

HAND_SCORED_FIXTURES: dict[str, dict[str, Any]] = {
    "stripe": {
        "dimensions": {
            "I1": 9.5,
            "I2": 9.0,
            "I3": 8.5,
            "I4": 9.5,
            "I5": 9.0,
            "I6": 8.0,
            "I7": 9.0,
            "F1": 9.0,
            "F2": 9.5,
            "F3": 9.5,
            "F4": 8.5,
            "F5": 10.0,
            "F6": 9.0,
            "F7": 9.0,
            "O1": 9.0,
            "O2": 9.0,
            "O3": 8.0,
        },
        "expected_score": 8.9,
        "access_dimensions": {
            "A1": 6.0,
            "A2": 5.5,
            "A3": 6.0,
            "A4": 7.5,
            "A5": 8.0,
            "A6": 8.0,
        },
        "evidence_count": 72,
        "freshness": "Initial evaluation",
        "probe_types": ["health", "auth", "schema", "load", "idempotency"],
        "production_telemetry": True,
        "active_failures": [
            {
                "id": "AF-oauth-redirect",
                "summary": "Token refresh requires browser redirect in security-sensitive flows",
            }
        ],
        "alternatives": [
            {"service": "square", "score": 7.4},
            {"service": "braintree", "score": 6.8},
        ],
    },
    "hubspot": {
        "dimensions": {
            "I1": 6.5,
            "I2": 6.0,
            "I3": 4.5,
            "I4": 6.0,
            "I5": 5.0,
            "I6": 6.0,
            "I7": 5.5,
            "F1": 6.0,
            "F2": 5.0,
            "F3": 6.0,
            "F4": 5.5,
            "F5": 4.0,
            "F6": 6.0,
            "F7": 4.0,
            "O1": 4.0,
            "O2": 5.0,
            "O3": 5.5,
        },
        "expected_score": 5.4,
        "access_dimensions": {
            "A1": 3.0,
            "A2": 3.0,
            "A3": 2.5,
            "A4": 3.0,
            "A5": 5.0,
            "A6": 6.0,
        },
        "evidence_count": 58,
        "freshness": "Initial evaluation",
        "probe_types": ["health", "auth", "schema", "functional"],
        "production_telemetry": True,
        "active_failures": [
            {"id": "SF-duplicate-contact", "summary": "Plus addressing creates duplicate contacts"},
            {"id": "SF-cache-stale", "summary": "Implicit 30-second cache returns stale CRM reads"},
        ],
        "alternatives": [
            {"service": "salesforce", "score": 6.1},
            {"service": "pipedrive", "score": 6.7},
        ],
    },
    "sendgrid": {
        "dimensions": {
            "I1": 8.0,
            "I2": 7.5,
            "I3": 8.0,
            "I4": 7.5,
            "I5": 8.0,
            "I6": 7.0,
            "I7": 7.0,
            "F1": 8.0,
            "F2": 7.0,
            "F3": 7.5,
            "F4": 7.5,
            "F5": 7.0,
            "F6": 7.5,
            "F7": 7.0,
            "O1": 7.0,
            "O2": 6.5,
            "O3": 6.0,
        },
        "expected_score": 7.4,
        "access_dimensions": {
            "A1": 4.5,
            "A2": 4.5,
            "A3": 4.5,
            "A4": 6.0,
            "A5": 7.0,
            "A6": 7.0,
        },
        "evidence_count": 54,
        "freshness": "Initial evaluation",
        "probe_types": ["health", "schema", "load", "webhook"],
        "production_telemetry": True,
        "active_failures": [
            {
                "id": "IN-webhook-p99",
                "summary": "Webhook P99 reaches 14s under load, forcing stateful retries",
            }
        ],
        "alternatives": [
            {"service": "resend", "score": 8.6},
            {"service": "postmark", "score": 7.8},
        ],
    },
    "resend": {
        "dimensions": {
            "I1": 8.5,
            "I2": 9.0,
            "I3": 9.0,
            "I4": 8.5,
            "I5": 8.5,
            "I6": 8.0,
            "I7": 8.0,
            "F1": 9.0,
            "F2": 9.0,
            "F3": 9.0,
            "F4": 8.0,
            "F5": 8.5,
            "F6": 9.0,
            "F7": 8.5,
            "O1": 9.0,
            "O2": 9.0,
            "O3": 8.0,
        },
        "expected_score": 8.6,
        "access_dimensions": {
            "A1": 6.5,
            "A2": 6.0,
            "A3": 6.5,
            "A4": 7.5,
            "A5": 7.5,
            "A6": 8.0,
        },
        "evidence_count": 33,
        "freshness": "Initial evaluation",
        "probe_types": ["health", "schema", "load", "webhook"],
        "production_telemetry": False,
        "active_failures": [],
        "alternatives": [
            {"service": "sendgrid", "score": 7.4},
            {"service": "postmark", "score": 7.8},
        ],
    },
    "github": {
        "dimensions": {
            "I1": 8.5,
            "I2": 8.0,
            "I3": 8.5,
            "I4": 8.0,
            "I5": 8.0,
            "I6": 7.5,
            "I7": 8.0,
            "F1": 8.0,
            "F2": 8.0,
            "F3": 8.5,
            "F4": 7.0,
            "F5": 8.0,
            "F6": 8.5,
            "F7": 8.0,
            "O1": 8.0,
            "O2": 7.5,
            "O3": 7.0,
        },
        "expected_score": 8.0,
        "access_dimensions": {
            "A1": 6.0,
            "A2": 5.5,
            "A3": 5.0,
            "A4": 6.5,
            "A5": 8.0,
            "A6": 8.5,
        },
        "evidence_count": 61,
        "freshness": "Initial evaluation",
        "probe_types": ["health", "auth", "schema", "functional", "webhook"],
        "production_telemetry": True,
        "active_failures": [
            {
                "id": "AF-oauth-redirect",
                "summary": "User-scoped OAuth still requires browser redirect in many workflows",
            }
        ],
        "alternatives": [
            {"service": "gitlab", "score": 7.2},
            {"service": "bitbucket", "score": 6.6},
        ],
    },
}
