#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVER_TS = ROOT / "packages/mcp/src/server.ts"
PUBLIC_TRUTH_TS = ROOT / "packages/astro-web/src/lib/public-truth.ts"
PUBLIC_TRUTH_COUNTS_TS = ROOT / "packages/astro-web/src/lib/public-truth-counts.ts"
OUTPUT_JSON = ROOT / "agent-capabilities.json"
WELL_KNOWN_OUTPUT_JSON = ROOT / "packages/astro-web/public/.well-known/agent-capabilities.json"
ASTRO_PUBLIC_OUTPUT_JSON = ROOT / "packages/astro-web/public/agent-capabilities.json"
LLMS_TXT = ROOT / "llms.txt"
WEB_PUBLIC_LLMS_TXT = ROOT / "packages/web/public/llms.txt"
ROOT_README = ROOT / "README.md"
MCP_README = ROOT / "packages/mcp/README.md"
WEB_PUBLIC_TRUTH_TS = ROOT / "packages/web/lib/public-truth.ts"
DEFAULT_API_BASE = "https://api.rhumb.dev/v1"

README_PRODUCT_START = "<!-- GENERATED:README_PRODUCT_SURFACE_START -->"
README_PRODUCT_END = "<!-- GENERATED:README_PRODUCT_SURFACE_END -->"
README_MCP_TOOLS_START = "<!-- GENERATED:README_MCP_TOOLS_START -->"
README_MCP_TOOLS_END = "<!-- GENERATED:README_MCP_TOOLS_END -->"
MCP_README_TOOL_SURFACE_START = "<!-- GENERATED:MCP_README_TOOL_SURFACE_START -->"
MCP_README_TOOL_SURFACE_END = "<!-- GENERATED:MCP_README_TOOL_SURFACE_END -->"
MCP_README_COVERAGE_START = "<!-- GENERATED:MCP_README_COVERAGE_START -->"
MCP_README_COVERAGE_END = "<!-- GENERATED:MCP_README_COVERAGE_END -->"


GROUPS: list[tuple[str, str, bool, list[str]]] = [
    (
        "discovery",
        "Search, score, and evaluate {services_label} services across {domains_label} capability domains",
        False,
        [
            "find_services",
            "get_score",
            "get_alternatives",
            "get_failure_modes",
            "discover_capabilities",
            "resolve_capability",
        ],
    ),
    (
        "execution",
        "Execute capabilities through Resolve on the live execution rail returned by resolve: governed API key, wallet-prefund, or x402 per-call, with BYOK or Agent Vault where supported",
        True,
        [
            "execute_capability",
            "estimate_capability",
            "credential_ceremony",
            "check_credentials",
            "rhumb_list_recipes",
            "rhumb_get_recipe",
            "rhumb_recipe_execute",
            "get_receipt",
        ],
    ),
    (
        "billing",
        "Budget enforcement and spend tracking",
        True,
        [
            "budget",
            "spend",
            "check_balance",
            "get_payment_url",
            "get_ledger",
        ],
    ),
    (
        "operations",
        "Routing preferences and usage analytics",
        True,
        ["routing", "usage_telemetry"],
    ),
]


def _count_label(value: int) -> str:
    return f"{value:,}"


def load_public_truth_counts() -> dict[str, int | str]:
    text = PUBLIC_TRUTH_COUNTS_TS.read_text()
    out: dict[str, int | str] = {}
    for key in [
        "source",
        "fetchedAt",
        "services",
        "capabilities",
        "categories",
        "capabilityDomains",
        "callableProviders",
        "registeredProviders",
        "mcpTools",
    ]:
        match = re.search(rf"^  {re.escape(key)}:\s*(\d+|\"[^\"]+\")", text, re.M)
        if not match:
            raise RuntimeError(f"Missing {key} in {PUBLIC_TRUTH_COUNTS_TS}")
        raw = match.group(1)
        out[key] = int(raw) if raw.isdigit() else raw.strip('"')
    return out


def render_public_truth_counts(counts: dict[str, int | str]) -> str:
    return (
        "/** Generated by `python3 scripts/generate_agent_capabilities.py --from-live`. Do not edit by hand. */\n"
        "export const PUBLIC_TRUTH_COUNTS = {\n"
        f'  source: "{counts["source"]}",\n'
        f'  fetchedAt: "{counts["fetchedAt"]}",\n'
        "  endpoints: {\n"
        '    services: "/v1/services?limit=1",\n'
        '    capabilities: "/v1/capabilities?limit=1",\n'
        '    capabilityDomains: "/v1/capabilities/domains",\n'
        '    proxyStats: "/v1/proxy/stats",\n'
        '    leaderboard: "/v1/leaderboard",\n'
        "  },\n"
        f"  services: {int(counts['services'])},\n"
        f"  capabilities: {int(counts['capabilities'])},\n"
        f"  categories: {int(counts['categories'])},\n"
        f"  capabilityDomains: {int(counts['capabilityDomains'])},\n"
        f"  callableProviders: {int(counts['callableProviders'])},\n"
        f"  registeredProviders: {int(counts['registeredProviders'])},\n"
        f"  mcpTools: {int(counts['mcpTools'])},\n"
        "} as const;\n"
    )


def fetch_live_public_truth_counts(api_base: str) -> dict[str, int | str]:
    def get(path: str) -> dict:
        url = f"{api_base.rstrip('/')}{path}"
        try:
            with urllib.request.urlopen(url, timeout=30) as response:
                payload = json.loads(response.read().decode())
        except urllib.error.URLError as exc:
            raise RuntimeError(f"Failed to fetch {url}: {exc}") from exc
        if not isinstance(payload, dict):
            raise RuntimeError(f"Unexpected payload from {url}")
        data = payload.get("data", payload)
        if not isinstance(data, dict):
            raise RuntimeError(f"Unexpected data envelope from {url}")
        return data

    services = get("/services?limit=1")
    capabilities = get("/capabilities?limit=1")
    capability_domains = get("/capabilities/domains")
    proxy = get("/proxy/stats")
    leaderboard = get("/leaderboard")

    domain_rows = capability_domains.get("domains")
    if not isinstance(domain_rows, list):
        raise RuntimeError("Live /capabilities/domains did not return a domains list")
    distinct_domains = {
        row["domain"]
        for row in domain_rows
        if isinstance(row, dict) and isinstance(row.get("domain"), str) and row["domain"]
    }

    counts = {
        "source": api_base.rstrip("/"),
        "fetchedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "services": int(services["total"]),
        "capabilities": int(capabilities["total"]),
        "categories": int(leaderboard["total"]),
        "capabilityDomains": len(distinct_domains),
        "callableProviders": int(proxy["services_callable"]),
        "registeredProviders": int(proxy["services_registered"]),
        "mcpTools": 21,
    }
    for key in ("services", "capabilities", "categories", "capabilityDomains", "callableProviders", "registeredProviders"):
        if int(counts[key]) <= 0:
            raise RuntimeError(f"Live public-truth counter {key} was {counts[key]}")
    return counts


def load_public_truth() -> dict[str, int | str]:
    counts = load_public_truth_counts()
    text = PUBLIC_TRUTH_TS.read_text()
    out: dict[str, int | str] = {
        "services": int(counts["services"]),
        "servicesLabel": _count_label(int(counts["services"])),
        "capabilities": int(counts["capabilities"]),
        "capabilitiesLabel": _count_label(int(counts["capabilities"])),
        "categories": int(counts["categories"]),
        "categoriesLabel": _count_label(int(counts["categories"])),
        "capabilityDomains": int(counts["capabilityDomains"]),
        "domainsLabel": _count_label(int(counts["capabilityDomains"])),
        "callableProviders": int(counts["callableProviders"]),
        "callableProvidersLabel": _count_label(int(counts["callableProviders"])),
        "registeredProviders": int(counts["registeredProviders"]),
        "registeredProvidersLabel": _count_label(int(counts["registeredProviders"])),
        "mcpTools": int(counts["mcpTools"]),
        "mcpToolsLabel": _count_label(int(counts["mcpTools"])),
        "fetchedAt": str(counts["fetchedAt"]),
        "source": str(counts["source"]),
    }
    for key in [
        "beachheadLabel",
        "beachheadSummary",
        "trustOverviewUrl",
        "methodologyUrl",
        "providersUrl",
        "llmsUrl",
        "publicAgentCapabilitiesUrl",
        "currentSelfAssessmentUrl",
        "historicalSelfAssessmentUrl",
        "publicDisputeTemplateUrl",
        "publicDisputesUrl",
        "privateDisputesEmail",
        "privateDisputeMailto",
        "disputeResponseSlaBusinessDays",
    ]:
        match = re.search(rf"{re.escape(key)}:\s*(\d+|\"[^\"]+\")", text)
        if not match:
            raise RuntimeError(f"Missing {key} in {PUBLIC_TRUTH_TS}")
        raw = match.group(1)
        out[key] = int(raw) if raw.isdigit() else raw.strip('"')
    return out


def extract_tools() -> dict[str, str]:
    text = SERVER_TS.read_text()
    pattern = re.compile(
        r'server\.tool\(\s*\n\s*"([^"]+)"\s*,\s*\n\s*"((?:[^"\\]|\\.)*)"',
        re.S,
    )
    tools: dict[str, str] = {}
    for name, description in pattern.findall(text):
        desc = ast.literal_eval(f'"{description}"')
        tools[name] = desc.split(". ", 1)[0].strip().rstrip(".")
    if len(tools) != 21:
        raise RuntimeError(f"Expected 21 MCP tools from {SERVER_TS}, got {len(tools)}")
    return tools


def build_agent_capabilities() -> dict:
    public_truth = load_public_truth()
    tools = extract_tools()

    capabilities: dict[str, dict] = {}
    for group_name, description_template, auth_required, tool_names in GROUPS:
        capabilities[group_name] = {
            "description": description_template.format(
                services_label=public_truth["servicesLabel"],
                domains_label=public_truth["domainsLabel"],
            ),
            "auth_required": auth_required,
            "tools": [
                {"name": tool_name, "description": tools[tool_name]}
                for tool_name in tool_names
            ],
        }

    return {
        "schema_version": "1.0",
        "name": "Rhumb",
        "description": f"Agent gateway for {public_truth['beachheadLabel']}: Rhumb Index scores and compares services; Rhumb Resolve routes supported capability calls through governed execution rails with receipts.",
        "homepage": "https://rhumb.dev",
        "api_base": "https://api.rhumb.dev/v1",
        "mcp_install": "npx rhumb-mcp@latest",
        "npm_package": "rhumb-mcp",
        "auth": {
            "discovery": "none",
            "execution": "rail_based",
            "repeat_traffic": "governed_api_key_or_wallet_prefund_on_x_rhumb_key",
            "zero_signup": "x402_usdc",
            "provider_control": "byok_or_agent_vault",
            "signup_url": "https://rhumb.dev/auth/login",
        },
        "capabilities": capabilities,
        "coverage": {
            "services": public_truth["services"],
            "capabilities": public_truth["capabilities"],
            "domains": public_truth["capabilityDomains"],
            "categories": public_truth["categories"],
            "providers_with_execution": public_truth["callableProviders"],
            "credential_modes": ["byok", "rhumb_managed", "agent_vault"],
        },
        "scoring": {
            "methodology": public_truth["methodologyUrl"],
            "dimensions": 20,
            "axes": {
                "execution": {
                    "weight": 0.70,
                    "dimensions": 13,
                    "includes_autonomy_dimensions": 3,
                },
                "access": {"weight": 0.30, "dimensions": 7},
            },
            "tiers": {
                "L4_Native": "8.0-10.0",
                "L3_Ready": "6.0-7.9",
                "L2_Developing": "4.0-5.9",
                "L1_Emerging": "0.0-3.9",
            },
        },
        "trust": {
            "overview": public_truth["trustOverviewUrl"],
            "methodology": public_truth["methodologyUrl"],
            "provider_guide": public_truth["providersUrl"],
            "machine_readable_docs": public_truth["llmsUrl"],
            "agent_capabilities": public_truth["publicAgentCapabilitiesUrl"],
            "current_self_assessment": public_truth["currentSelfAssessmentUrl"],
            "historical_self_assessment": public_truth["historicalSelfAssessmentUrl"],
            "public_dispute_template": public_truth["publicDisputeTemplateUrl"],
            "public_dispute_log": public_truth["publicDisputesUrl"],
            "private_dispute_email": public_truth["privateDisputesEmail"],
            "private_dispute_mailto": public_truth["privateDisputeMailto"],
            "dispute_response_sla_business_days": public_truth["disputeResponseSlaBusinessDays"],
        },
        "pricing": {
            "discovery": "free",
            "execution": "rail_based",
            "free_tier": None,
            "details": "https://rhumb.dev/pricing",
        },
        "links": {
            "quickstart": "https://rhumb.dev/quickstart",
            "trust": public_truth["trustOverviewUrl"],
            "methodology": public_truth["methodologyUrl"],
            "providers": public_truth["providersUrl"],
            "blog": "https://rhumb.dev/blog",
            "github": "https://github.com/supertrained/rhumb",
            "disputes": public_truth["providersUrl"],
        },
    }


def render_tool_bullets(tool_names: list[str], tools: dict[str, str]) -> str:
    return "\n".join(f"- `{tool_name}` — {tools[tool_name]}" for tool_name in tool_names)


def render_tool_table(tool_names: list[str], tools: dict[str, str]) -> str:
    rows = ["| Tool | What it does |", "|------|-------------|"]
    rows.extend(f"| `{tool_name}` | {tools[tool_name]} |" for tool_name in tool_names)
    return "\n".join(rows)


def render_root_product_surface(public_truth: dict[str, int | str], tools: dict[str, str]) -> str:
    return f"""### Rhumb Index — Discover & Evaluate

**{public_truth['servicesLabel']} scored services** across {public_truth['domainsLabel']} capability domains. Each gets an [AN Score](https://rhumb.dev/methodology) (0–10) measuring execution quality, access readiness, and agent autonomy support.

{render_tool_bullets(GROUPS[0][3], tools)}

> Discovery breadth is wider than current execution coverage. The index is broader than what Rhumb can execute today.

### Rhumb Resolve — Execute

**{public_truth['capabilitiesLabel']} capability definitions** across **{public_truth['callableProvidersLabel']} callable providers today**. Resolve chooses the best-fit supported provider for the call using AN Score, availability / circuit state, estimated cost, latency proxy, credential mode, and explicit policy constraints.

- `execute_capability` — {tools['execute_capability']}
- `resolve_capability` — {tools['resolve_capability']}
- `estimate_capability` — {tools['estimate_capability']}
- `get_receipt` — {tools['get_receipt']}
- Budget enforcement, credential management, and execution telemetry included

> Best current fit: {public_truth['beachheadLabel']}. Treat general business-agent automation and broad multi-system orchestration as future scope, not the current callable promise."""


def render_root_mcp_tools(public_truth: dict[str, int | str], tools: dict[str, str]) -> str:
    sections: list[str] = [f"`rhumb-mcp` exposes **{public_truth['mcpToolsLabel']} tools**:"]
    for group_name, _, _, tool_names in GROUPS:
        title = group_name.capitalize()
        sections.append(f"\n**{title}**\n{render_tool_bullets(tool_names, tools)}")
    sections.append(
        f"\n> Discovery spans {public_truth['servicesLabel']} scored services, but current governed execution spans {public_truth['callableProvidersLabel']} callable providers."
    )
    sections.append(
        "\n> Note: Layer 3 recipe tooling is live, but the public catalog can still be empty. Use `rhumb_list_recipes` or visit `/recipes` before assuming a workflow exists."
    )
    sections.append(
        f"\n> Best current fit: {public_truth['beachheadLabel']}. Treat general business-agent automation as future scope, not the current callable promise."
    )
    return "\n".join(sections)


def render_mcp_readme_tool_surface(public_truth: dict[str, int | str], tools: dict[str, str]) -> str:
    sections: list[str] = []
    sections.append(f"## Discovery tools (no auth, {len(GROUPS[0][3])} tools)\n\n{render_tool_table(GROUPS[0][3], tools)}")
    sections.append(f"## Execution tools (auth required, {len(GROUPS[1][3])} tools)\n\n```json\n{{\n  \"mcpServers\": {{\n    \"rhumb\": {{\n      \"command\": \"npx\",\n      \"args\": [\"-y\", \"rhumb-mcp@latest\"],\n      \"env\": {{\n        \"RHUMB_API_KEY\": \"rk_your_key_here\"\n      }}\n    }}\n  }}\n}}\n```\n\nGet a governed API key at https://rhumb.dev/auth/login (GitHub, Google, or email — 30 seconds).\n\n{render_tool_table(GROUPS[1][3], tools)}")
    sections.append(f"## Financial tools (auth required, {len(GROUPS[2][3])} tools)\n\n{render_tool_table(GROUPS[2][3], tools)}")
    sections.append(f"## Operations tools (auth required, {len(GROUPS[3][3])} tools)\n\n{render_tool_table(GROUPS[3][3], tools)}")
    sections.append(
        f"## {public_truth['mcpToolsLabel']} MCP tools\n\n"
        f"**Discovery (free):** {', '.join(f'`{name}`' for name in GROUPS[0][3])}\n\n"
        f"**Execution (auth):** {', '.join(f'`{name}`' for name in GROUPS[1][3])}\n\n"
        f"**Financial (auth):** {', '.join(f'`{name}`' for name in GROUPS[2][3])}\n\n"
        f"**Operations (auth):** {', '.join(f'`{name}`' for name in GROUPS[3][3])}\n\n"
        f"> Discovery spans {public_truth['servicesLabel']} scored services, but current governed execution spans {public_truth['callableProvidersLabel']} callable providers.\n\n"
        f"> Best current fit: {public_truth['beachheadLabel']}. Treat general business-agent automation as future scope, not the current callable promise."
    )
    return "\n\n".join(sections)


def render_llms_txt(public_truth: dict[str, int | str], tools: dict[str, str]) -> str:
    return f"""# Rhumb — Agent-Native Tool Intelligence
> Canonical public docs: https://rhumb.dev/llms.txt

## What is Rhumb?
Rhumb is an agent gateway: Rhumb Index scores and compares services; Rhumb Resolve routes supported capability calls through governed execution rails with receipts.

## Current callable scope
- Best current fit: {public_truth['beachheadLabel']}
- Not the current promise: general business-agent automation or broad multi-system workflow orchestration

## Primary surfaces
- Website: https://rhumb.dev
- API: https://api.rhumb.dev/v1
- MCP: npx rhumb-mcp@latest
- npm: https://www.npmjs.com/package/rhumb-mcp

## Current coverage
- {public_truth['servicesLabel']} scored services across {public_truth['domainsLabel']} capability domains
- {public_truth['capabilitiesLabel']} capability definitions
- {public_truth['categoriesLabel']} categories
- {public_truth['callableProvidersLabel']} callable providers
- {public_truth['mcpToolsLabel']} MCP tools
- 3 execution rails: governed API key, wallet-prefund, x402 / USDC
- 2 operator-controlled credential modes where supported: BYOK, Agent Vault

## Honest current state
- Discovery breadth is wider than execution breadth
- The index covers {public_truth['servicesLabel']} scored services and {public_truth['capabilitiesLabel']} capability definitions
- Current governed execution surface is {public_truth['callableProvidersLabel']} callable providers
- Best current fit remains {public_truth['beachheadLabel']}

## Discovery (no auth)
- GET https://api.rhumb.dev/v1/search?q={{query}} — search services
- GET https://api.rhumb.dev/v1/services/{{slug}} — service profile, including scored same-category alternatives
- GET https://api.rhumb.dev/v1/services/{{slug}}/alternatives — scored same-category peers
- GET https://api.rhumb.dev/v1/services/{{slug}}/score — AN Score breakdown
- GET https://api.rhumb.dev/v1/services/{{slug}}/failures — known failure modes (empty list is a coverage gap, not a clean bill of health)
- GET https://api.rhumb.dev/v1/capabilities — browse capability registry
- GET https://api.rhumb.dev/v1/capabilities/{{id}}/resolve — ranked providers
- GET https://api.rhumb.dev/v1/leaderboard/{{category}} — category rankings
- GET https://api.rhumb.dev/v1/telemetry/provider-health — provider health status
- GET https://api.rhumb.dev/v1/pricing — machine-readable pricing

## Execution (requires a live rail)
- POST https://api.rhumb.dev/v1/capabilities/{{id}}/execute — execute a capability
- GET https://api.rhumb.dev/v1/capabilities/{{id}}/execute/estimate — estimate the active execution rail, cost, and health before execution; anonymous direct system-of-record paths also preserve machine-readable execute_readiness handoffs

## Execution rails
1. Governed API key: sign up at https://rhumb.dev/auth/login, then send X-Rhumb-Key on the governed rail
2. Wallet-prefund: add balance first, then execute with X-Rhumb-Key on the governed rail
3. x402 / USDC: no signup, pay per call, send X-Payment header

## Operator-controlled credential modes
- BYOK credentials: pass your own upstream API keys when provider control is the point
- Agent Vault: when supported, let Rhumb inject the provider credential at call time while keeping the raw secret behind Rhumb

## MCP tools ({public_truth['mcpToolsLabel']} total)
Discovery: {', '.join(GROUPS[0][3])}
Execution: {', '.join(GROUPS[1][3])}
Billing: {', '.join(GROUPS[2][3])}
Operations: {', '.join(GROUPS[3][3])}

## Key tool semantics
- find_services — {tools['find_services']}
- get_score — {tools['get_score']}
- resolve_capability — {tools['resolve_capability']}
- execute_capability — {tools['execute_capability']}
- estimate_capability — {tools['estimate_capability']}
- get_receipt — {tools['get_receipt']}
- usage_telemetry — {tools['usage_telemetry']}

## Pricing
- Discovery: free, no auth
- Execution rails: governed API key, wallet-prefund, or x402 per-call
- Provider-control modes where supported: BYOK and Agent Vault
- No subscriptions, no seat fees, no minimums
- Live pricing and markup terms: https://rhumb.dev/pricing

## Trust and disputes
- Trust overview: {public_truth['trustOverviewUrl']}
- Methodology: {public_truth['methodologyUrl']}
- Current self-assessment: {public_truth['currentSelfAssessmentUrl']}
- Historical baseline: {public_truth['historicalSelfAssessmentUrl']}
- Provider guide and dispute process: {public_truth['providersUrl']}
- Public dispute template: {public_truth['publicDisputeTemplateUrl']}
- Public dispute log: {public_truth['publicDisputesUrl']}
- Private disputes: {public_truth['privateDisputeMailto']}
- Dispute response target: {public_truth['disputeResponseSlaBusinessDays']} business days

## Links
- Quickstart: https://rhumb.dev/quickstart
- Pricing: https://rhumb.dev/pricing
- Blog: https://rhumb.dev/blog
- GitHub: https://github.com/supertrained/rhumb
- Public agent capabilities: {public_truth['publicAgentCapabilitiesUrl']}""" + "\n"


def replace_managed_block(text: str, start_marker: str, end_marker: str, body: str) -> str:
    pattern = re.compile(rf"{re.escape(start_marker)}.*?{re.escape(end_marker)}", re.S)
    if not pattern.search(text):
        raise RuntimeError(f"Missing managed block markers: {start_marker} ... {end_marker}")
    replacement = f"{start_marker}\n{body.rstrip()}\n{end_marker}"
    return pattern.sub(replacement, text, count=1)


def build_readme_outputs(public_truth: dict[str, int | str], tools: dict[str, str]) -> dict[Path, str]:
    agent_contract = json.dumps(build_agent_capabilities(), indent=2, ensure_ascii=False) + "\n"

    root_readme = ROOT_README.read_text()
    root_readme = replace_managed_block(
        root_readme,
        README_PRODUCT_START,
        README_PRODUCT_END,
        render_root_product_surface(public_truth, tools),
    )
    root_readme = replace_managed_block(
        root_readme,
        README_MCP_TOOLS_START,
        README_MCP_TOOLS_END,
        render_root_mcp_tools(public_truth, tools),
    )

    mcp_readme = MCP_README.read_text()
    mcp_readme = replace_managed_block(
        mcp_readme,
        MCP_README_COVERAGE_START,
        MCP_README_COVERAGE_END,
        (
            "Discovery breadth is wider than current execution breadth: "
            f"Rhumb scores **{public_truth['servicesLabel']} services** and exposes "
            f"**{public_truth['capabilitiesLabel']} capability definitions**, but current "
            f"governed execution is concentrated in **{public_truth['callableProvidersLabel']} callable providers**."
        ),
    )
    mcp_readme = replace_managed_block(
        mcp_readme,
        MCP_README_TOOL_SURFACE_START,
        MCP_README_TOOL_SURFACE_END,
        render_mcp_readme_tool_surface(public_truth, tools),
    )

    llms_txt = render_llms_txt(public_truth, tools)

    visibility_old = re.search(
        r"\d+ runtime-callable providers today",
        root_readme,
    )
    if visibility_old:
        root_readme = root_readme.replace(
            visibility_old.group(0),
            f"{public_truth['callableProvidersLabel']} runtime-callable providers today",
            1,
        )

    web_public_truth = WEB_PUBLIC_TRUTH_TS.read_text()
    web_public_truth = re.sub(
        r'servicesLabel:\s*"[^"]+"',
        f'servicesLabel: "{public_truth["servicesLabel"]}"',
        web_public_truth,
        count=1,
    )
    web_public_truth = re.sub(
        r'categoriesLabel:\s*"[^"]+"',
        f'categoriesLabel: "{public_truth["categoriesLabel"]}"',
        web_public_truth,
        count=1,
    )

    return {
        OUTPUT_JSON: agent_contract,
        WELL_KNOWN_OUTPUT_JSON: agent_contract,
        ASTRO_PUBLIC_OUTPUT_JSON: agent_contract,
        LLMS_TXT: llms_txt,
        WEB_PUBLIC_LLMS_TXT: llms_txt,
        ROOT_README: root_readme,
        MCP_README: mcp_readme,
        WEB_PUBLIC_TRUTH_TS: web_public_truth,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate public truth surfaces from live repo truth")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if generated truth surfaces are out of date")
    parser.add_argument("--write", action="store_true", help="Write generated truth surfaces to disk")
    parser.add_argument(
        "--from-live",
        action="store_true",
        help="Refresh public-truth-counts.ts from the live public API before generating",
    )
    parser.add_argument(
        "--api-base",
        default=os.environ.get("RHUMB_API_BASE", DEFAULT_API_BASE),
        help=f"Public API base used by --from-live (default {DEFAULT_API_BASE})",
    )
    args = parser.parse_args()

    if args.from_live:
        live_counts = fetch_live_public_truth_counts(args.api_base)
        PUBLIC_TRUTH_COUNTS_TS.write_text(render_public_truth_counts(live_counts))
        print(f"wrote {PUBLIC_TRUTH_COUNTS_TS}")

    public_truth = load_public_truth()
    tools = extract_tools()
    rendered_files = build_readme_outputs(public_truth, tools)

    if args.check:
        stale_files = []
        for path, rendered in rendered_files.items():
            current = path.read_text() if path.exists() else ""
            if current != rendered:
                stale_files.append(path.relative_to(ROOT).as_posix())
        if stale_files:
            print("Generated truth surfaces are out of date:")
            for path in stale_files:
                print(f"- {path}")
            return 1
        print("Generated truth surfaces are up to date")
        return 0

    if args.write or args.from_live:
        for path, rendered in rendered_files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered)
            print(f"wrote {path}")
        return 0

    print(rendered_files[OUTPUT_JSON], end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
