/** Generated by `python3 scripts/generate_agent_capabilities.py --from-live`. Do not edit by hand. */
export const PUBLIC_TRUTH_COUNTS = {
  source: "https://api.rhumb.dev/v1",
  fetchedAt: "2026-09-10T04:28:41Z",
  endpoints: {
    services: "/v1/services?limit=1",
    capabilities: "/v1/capabilities?limit=1",
    capabilityDomains: "/v1/capabilities/domains",
    proxyStats: "/v1/proxy/stats",
    leaderboard: "/v1/leaderboard",
  },
  services: 999,
  capabilities: 435,
  categories: 87,
  capabilityDomains: 149,
  callableProviders: 28,
  registeredProviders: 29,
  mcpTools: 21,
} as const;
